///////////////////////////////////////////////////////////////////////////////////////////
// This is the centralized header files for all gen_xxx.h/cpp files created by autogen.
// TODO: It's manually created rightnow. Need to be generated by autogen
///////////////////////////////////////////////////////////////////////////////////////////

#ifndef __COMMON_HEADER_AUTOGEN_H__
#define __COMMON_HEADER_AUTOGEN_H__

#include "temp_table.h"
#include "gen_reserved.h"
#include "gen_literal.h"
#include "gen_iden.h"
#include "gen_type.h"

#endif
