///////////////////////////////////////////////////////////////////////////////////////////
// This is the centralized header files for all gen_xxx.h/cpp files created by autogen.
// TODO: It's manually created rightnow. Need to be generated by autogen
///////////////////////////////////////////////////////////////////////////////////////////

#ifndef __COMMON_HEADER_AUTOGEN_H__
#define __COMMON_HEADER_AUTOGEN_H__

#include "ruletable.h"
#include "gen_reserved.h"
#include "gen_literal.h"
#include "gen_iden.h"
#include "gen_type.h"
#include "gen_expr.h"
#include "gen_stmt.h"
#include "gen_block.h"
#include "gen_separator.h"
#include "gen_operator.h"
#include "gen_keyword.h"

#endif
