/*
* Copyright (C) [2020] Futurewei Technologies, Inc. All rights reverved.
*
* OpenArkFE is licensed under the Mulan PSL v2.
* You can use this software according to the terms and conditions of the Mulan PSL v2.
* You may obtain a copy of Mulan PSL v2 at:
*
*  http://license.coscl.org.cn/MulanPSL2
*
* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR
* FIT FOR A PARTICULAR PURPOSE.
* See the Mulan PSL v2 for more details.
*/
///////////////////////////////////////////////////////////////////////////////////////////
// This is the centralized header files for all gen_xxx.h/cpp files created by autogen.
// TODO: It's manually created rightnow. Need to be generated by autogen
///////////////////////////////////////////////////////////////////////////////////////////

#ifndef __COMMON_HEADER_AUTOGEN_H__
#define __COMMON_HEADER_AUTOGEN_H__

#include <cstddef>

#include "ruletable.h"
#include "gen_reserved.h"
#include "gen_literal.h"
#include "gen_iden.h"
#include "gen_type.h"
#include "gen_stmt.h"
#include "gen_separator.h"
#include "gen_operator.h"
#include "gen_keyword.h"

#endif
