#ifndef __global_vars_h__
#define __global_vars_h__

static signed short int *global_pointer_signed_short_int_1 = NULL;
static struct struct0  *global_pointer_struct_struct0_1 = NULL;
static struct struct0  global_struct_struct0_1;
static signed short int global_signed_short_int_1 = /* LITERAL */ (signed short int) 8388;
static signed int global_array_5_signed_int_1[5];
static double global_double_1 = /* LITERAL */ (double) 1.6573567494374555e+308;
static bool global_bool_1 = false;
static unsigned long long int **global_pointer_pointer_unsigned_long_long_int_1 = NULL;
static struct struct1  global_struct_struct1_1;
static struct struct1  **global_pointer_pointer_struct_struct1_1 = NULL;
static signed int global_signed_int_1 = /* LITERAL */ (signed int) 1890803674;
static signed long int global_array_2_signed_long_int_1[2];
static unsigned char global_unsigned_char_1 = 182U;
static signed int *global_pointer_signed_int_1 = NULL;
static unsigned long int global_unsigned_long_int_1 = 3583235821UL;
static signed long long int (*global_pointer_array_5_signed_long_long_int_1)[5] = NULL;
static signed long int global_signed_long_int_1 = -807071461L;
static signed long int global_signed_long_int_2 = 691940590L;
static bool (*global_pointer_array_1_bool_1)[1] = NULL;
static struct struct1  *global_pointer_struct_struct1_1 = NULL;
static unsigned short int global_unsigned_short_int_1 = 61585U;
static bool global_array_6_bool_1[6];
static signed char global_signed_char_1 = /* LITERAL */ (signed char) -3;
static signed char global_signed_char_2 = /* LITERAL */ (signed char) -43;
static signed long long int global_signed_long_long_int_1 = 592797371024599937LL;
static float ***global_pointer_pointer_pointer_float_1 = NULL;
static signed short int **global_pointer_pointer_signed_short_int_1 = NULL;
static struct struct2  *global_array_8_pointer_struct_struct2_1[8];
static struct struct3  *global_array_5_pointer_struct_struct3_1[5];
static unsigned char **global_pointer_pointer_unsigned_char_1 = NULL;
static unsigned int global_unsigned_int_1 = 4123212846U;
static unsigned char *global_pointer_unsigned_char_1 = "tkMChf615Lw1Jcz90rjrTTDLKT";
static unsigned long long int global_unsigned_long_long_int_1 = 12555378492034730318ULL;
static unsigned long long int global_unsigned_long_long_int_2 = 4747384395032661624ULL;
static struct struct2  global_struct_struct2_1;
static float **global_pointer_pointer_float_1 = NULL;
static unsigned char global_array_8_unsigned_char_1[8];
static struct struct6  *global_pointer_struct_struct6_1 = NULL;
static unsigned long int *global_array_9_pointer_unsigned_long_int_1[9];
static float *global_pointer_float_1 = NULL;
static struct struct2  *global_pointer_struct_struct2_1 = NULL;
static unsigned char (**global_pointer_pointer_array_8_unsigned_char_1)[8] = NULL;
static unsigned long int *global_pointer_unsigned_long_int_1 = NULL;
static unsigned long int global_array_6_unsigned_long_int_1[6];
static float global_float_1 = /* LITERAL */ (float) 3.3060160755169525e+38;
static signed char *global_pointer_signed_char_1 = "ymo2SSl0SzUao";
static unsigned char **global_array_1_pointer_pointer_unsigned_char_1[1];
static unsigned int global_array_3_unsigned_int_1[3] = { 4280423329U, 4221351715U, 693396179U };
static struct struct5  global_struct_struct5_1;
static struct struct3  *global_pointer_struct_struct3_1 = NULL;
static signed char global_array_6_signed_char_1[6];
static struct struct0  global_array_9_struct_struct0_1[9];
static struct struct9  *global_pointer_struct_struct9_1 = NULL;
static struct struct10  *global_pointer_struct_struct10_1 = NULL;
static double *global_pointer_double_1 = NULL;
static signed long int *global_pointer_signed_long_int_1 = NULL;
static unsigned short int (*global_pointer_array_6_unsigned_short_int_1)[6] = NULL;
static unsigned char (*global_pointer_array_2_unsigned_char_1)[2] = NULL;
static signed char (*global_pointer_array_8_signed_char_1)[8] = NULL;
static bool *global_pointer_bool_1 = NULL;
static struct struct7  global_struct_struct7_1 = { .pointer_double_0 = NULL };
static struct struct6  **global_pointer_pointer_struct_struct6_1 = NULL;
static struct struct0  **global_pointer_pointer_struct_struct0_1 = NULL;
static signed long int global_array_4_signed_long_int_1[4];
static struct struct11  global_struct_struct11_1;
static unsigned short int (*global_pointer_array_3_unsigned_short_int_1)[3] = NULL;
static unsigned int *global_pointer_unsigned_int_1 = NULL;
static struct struct12  global_struct_struct12_1;
static float global_array_8_float_1[8];
static bool global_array_5_bool_1[5];
static signed int *(*global_pointer_array_9_pointer_signed_int_1)[9] = NULL;
static struct struct0  *global_array_2_pointer_struct_struct0_1[2];
static unsigned char global_array_1_unsigned_char_1[1];
static unsigned long int global_array_5_unsigned_long_int_1[5] = { 3674003780UL, 499859140UL, 2852414259UL, 1924627370UL, 1355005978UL };
static struct struct12  *global_pointer_struct_struct12_1 = NULL;
static struct struct14  global_array_5_struct_struct14_1[5];
static struct struct6  global_struct_struct6_1 = {.pointer_signed_short_int_0 = NULL, .pointer_struct_struct0_1 = NULL,
    .array_4_signed_long_int_2 = { -64516496L, 900633063L, 513604919L, 1440464860L },
    .signed_char_3 = /* LITERAL */ (signed char) 19 };
static unsigned int global_array_3_array_3_unsigned_int_1[3][3];
static double global_array_6_double_1[6];
static struct struct3  global_struct_struct3_1;
static signed char global_array_9_signed_char_1[9];
static struct struct2  (*global_pointer_array_8_struct_struct2_1)[8] = NULL;

#endif
