#include "common_header_autogen.h"
Action TblPackageName_sub1_action[1] = {{ACT_BuildField,2,{1,3}}};
TableData TblPackageName_sub1_data[3] ={{DT_Subtable, &TblPackageName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblPackageName_sub1 ={ET_Concatenate, RP_NA, 3, TblPackageName_sub1_data, 1, TblPackageName_sub1_action};
TableData TblPackageName_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblPackageName_sub1}};
RuleTable TblPackageName ={ET_Oneof, RP_NA, 2, TblPackageName_data, 0, NULL};
Action TblTypeName_sub1_action[1] = {{ACT_BuildField,2,{1,3}}};
TableData TblTypeName_sub1_data[3] ={{DT_Subtable, &TblPackageOrTypeName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblTypeName_sub1 ={ET_Concatenate, RP_NA, 3, TblTypeName_sub1_data, 1, TblTypeName_sub1_action};
TableData TblTypeName_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblTypeName_sub1}};
RuleTable TblTypeName ={ET_Oneof, RP_NA, 2, TblTypeName_data, 0, NULL};
Action TblPackageOrTypeName_sub1_action[1] = {{ACT_BuildField,2,{1,3}}};
TableData TblPackageOrTypeName_sub1_data[3] ={{DT_Subtable, &TblPackageOrTypeName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblPackageOrTypeName_sub1 ={ET_Concatenate, RP_NA, 3, TblPackageOrTypeName_sub1_data, 1, TblPackageOrTypeName_sub1_action};
TableData TblPackageOrTypeName_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblPackageOrTypeName_sub1}};
RuleTable TblPackageOrTypeName ={ET_Oneof, RP_NA, 2, TblPackageOrTypeName_data, 0, NULL};
Action TblExpressionName_sub1_action[1] = {{ACT_BuildField,2,{1,3}}};
TableData TblExpressionName_sub1_data[3] ={{DT_Subtable, &TblAmbiguousName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblExpressionName_sub1 ={ET_Concatenate, RP_NA, 3, TblExpressionName_sub1_data, 1, TblExpressionName_sub1_action};
TableData TblExpressionName_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblExpressionName_sub1}};
RuleTable TblExpressionName ={ET_Oneof, RP_NA, 2, TblExpressionName_data, 0, NULL};
TableData TblMethodName_data[1] ={{DT_Subtable, &TblIdentifier}};
RuleTable TblMethodName ={ET_Data, RP_NA, 1, TblMethodName_data, 0, NULL};
Action TblAmbiguousName_sub1_action[1] = {{ACT_BuildField,2,{1,3}}};
TableData TblAmbiguousName_sub1_data[3] ={{DT_Subtable, &TblAmbiguousName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblAmbiguousName_sub1 ={ET_Concatenate, RP_NA, 3, TblAmbiguousName_sub1_data, 1, TblAmbiguousName_sub1_action};
TableData TblAmbiguousName_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblAmbiguousName_sub1}};
RuleTable TblAmbiguousName ={ET_Oneof, RP_NA, 2, TblAmbiguousName_data, 0, NULL};
TableData TblClass_data[1] ={{DT_Token, {.mTokenId=87}}};
RuleTable TblClass ={ET_Data, RP_NA, 1, TblClass_data, 0, NULL};
TableData TblClassLiteral_sub3_data[2] ={{DT_Token, {.mTokenId=47}},{DT_Token, {.mTokenId=46}}};
RuleTable TblClassLiteral_sub3 ={ET_Concatenate, RP_NA, 2, TblClassLiteral_sub3_data, 0, NULL};
TableData TblClassLiteral_sub2_data[1] ={{DT_Subtable, &TblClassLiteral_sub3}};
RuleTable TblClassLiteral_sub2 ={ET_Zeroormore, RP_NA, 1, TblClassLiteral_sub2_data, 0, NULL};
TableData TblClassLiteral_sub1_data[4] ={{DT_Subtable, &TblTypeName},{DT_Subtable, &TblClassLiteral_sub2},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblClass}};
RuleTable TblClassLiteral_sub1 ={ET_Concatenate, RP_NA, 4, TblClassLiteral_sub1_data, 0, NULL};
TableData TblClassLiteral_sub6_data[2] ={{DT_Token, {.mTokenId=47}},{DT_Token, {.mTokenId=46}}};
RuleTable TblClassLiteral_sub6 ={ET_Concatenate, RP_NA, 2, TblClassLiteral_sub6_data, 0, NULL};
TableData TblClassLiteral_sub5_data[1] ={{DT_Subtable, &TblClassLiteral_sub6}};
RuleTable TblClassLiteral_sub5 ={ET_Zeroormore, RP_NA, 1, TblClassLiteral_sub5_data, 0, NULL};
TableData TblClassLiteral_sub4_data[4] ={{DT_Subtable, &TblNumericType},{DT_Subtable, &TblClassLiteral_sub5},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblClass}};
RuleTable TblClassLiteral_sub4 ={ET_Concatenate, RP_NA, 4, TblClassLiteral_sub4_data, 0, NULL};
TableData TblClassLiteral_sub9_data[2] ={{DT_Token, {.mTokenId=47}},{DT_Token, {.mTokenId=46}}};
RuleTable TblClassLiteral_sub9 ={ET_Concatenate, RP_NA, 2, TblClassLiteral_sub9_data, 0, NULL};
TableData TblClassLiteral_sub8_data[1] ={{DT_Subtable, &TblClassLiteral_sub9}};
RuleTable TblClassLiteral_sub8 ={ET_Zeroormore, RP_NA, 1, TblClassLiteral_sub8_data, 0, NULL};
TableData TblClassLiteral_sub7_data[4] ={{DT_Token, {.mTokenId=68}},{DT_Subtable, &TblClassLiteral_sub8},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblClass}};
RuleTable TblClassLiteral_sub7 ={ET_Concatenate, RP_NA, 4, TblClassLiteral_sub7_data, 0, NULL};
TableData TblClassLiteral_sub10_data[3] ={{DT_Token, {.mTokenId=92}},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblClass}};
RuleTable TblClassLiteral_sub10 ={ET_Concatenate, RP_NA, 3, TblClassLiteral_sub10_data, 0, NULL};
TableData TblClassLiteral_data[4] ={{DT_Subtable, &TblClassLiteral_sub1},{DT_Subtable, &TblClassLiteral_sub4},{DT_Subtable, &TblClassLiteral_sub7},{DT_Subtable, &TblClassLiteral_sub10}};
RuleTable TblClassLiteral ={ET_Oneof, RP_Single, 4, TblClassLiteral_data, 0, NULL};
TableData TblPrimaryNoNewArray_single_sub1_data[3] ={{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=43}},{DT_Token, {.mTokenId=88}}};
RuleTable TblPrimaryNoNewArray_single_sub1 ={ET_Concatenate, RP_NA, 3, TblPrimaryNoNewArray_single_sub1_data, 0, NULL};
Action TblPrimaryNoNewArray_single_sub2_action[1] = {{ACT_BuildParenthesis,1,{2}}};
TableData TblPrimaryNoNewArray_single_sub2_data[3] ={{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}}};
RuleTable TblPrimaryNoNewArray_single_sub2 ={ET_Concatenate, RP_NA, 3, TblPrimaryNoNewArray_single_sub2_data, 1, TblPrimaryNoNewArray_single_sub2_action};
TableData TblPrimaryNoNewArray_single_data[6] ={{DT_Subtable, &TblLiteral},{DT_Subtable, &TblClassLiteral},{DT_Token, {.mTokenId=88}},{DT_Subtable, &TblPrimaryNoNewArray_single_sub1},{DT_Subtable, &TblPrimaryNoNewArray_single_sub2},{DT_Subtable, &TblClassInstanceCreationExpression}};
RuleTable TblPrimaryNoNewArray_single ={ET_Oneof, RP_Single, 6, TblPrimaryNoNewArray_single_data, 0, NULL};
TableData TblPrimaryNoNewArray_data[5] ={{DT_Subtable, &TblPrimaryNoNewArray_single},{DT_Subtable, &TblFieldAccess},{DT_Subtable, &TblArrayAccess},{DT_Subtable, &TblMethodInvocation},{DT_Subtable, &TblMethodReference}};
RuleTable TblPrimaryNoNewArray ={ET_Oneof, RP_NA, 5, TblPrimaryNoNewArray_data, 0, NULL};
TableData TblClassInstanceCreationExpression_sub1_data[3] ={{DT_Subtable, &TblPrimary},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblUnqualifiedClassInstanceCreationExpression}};
RuleTable TblClassInstanceCreationExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblClassInstanceCreationExpression_sub1_data, 0, NULL};
TableData TblClassInstanceCreationExpression_data[2] ={{DT_Subtable, &TblUnqualifiedClassInstanceCreationExpression},{DT_Subtable, &TblClassInstanceCreationExpression_sub1}};
RuleTable TblClassInstanceCreationExpression ={ET_Oneof, RP_NA, 2, TblClassInstanceCreationExpression_data, 0, NULL};
Action TblUnqualifiedClassInstanceCreationExpression_action[1] = {{ACT_BuildNewOperation,3,{3,5,7}}};
TableData TblUnqualifiedClassInstanceCreationExpression_sub1_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblUnqualifiedClassInstanceCreationExpression_sub1 ={ET_Zeroorone, RP_NA, 1, TblUnqualifiedClassInstanceCreationExpression_sub1_data, 0, NULL};
TableData TblUnqualifiedClassInstanceCreationExpression_sub2_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblUnqualifiedClassInstanceCreationExpression_sub2 ={ET_Zeroorone, RP_NA, 1, TblUnqualifiedClassInstanceCreationExpression_sub2_data, 0, NULL};
TableData TblUnqualifiedClassInstanceCreationExpression_sub3_data[1] ={{DT_Subtable, &TblClassBody}};
RuleTable TblUnqualifiedClassInstanceCreationExpression_sub3 ={ET_Zeroorone, RP_NA, 1, TblUnqualifiedClassInstanceCreationExpression_sub3_data, 0, NULL};
TableData TblUnqualifiedClassInstanceCreationExpression_data[7] ={{DT_Token, {.mTokenId=97}},{DT_Subtable, &TblUnqualifiedClassInstanceCreationExpression_sub1},{DT_Subtable, &TblClassOrInterfaceTypeToInstantiate},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblUnqualifiedClassInstanceCreationExpression_sub2},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblUnqualifiedClassInstanceCreationExpression_sub3}};
RuleTable TblUnqualifiedClassInstanceCreationExpression ={ET_Concatenate, RP_NA, 7, TblUnqualifiedClassInstanceCreationExpression_data, 1, TblUnqualifiedClassInstanceCreationExpression_action};
TableData TblClassOrInterfaceTypeToInstantiate_sub1_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblClassOrInterfaceTypeToInstantiate_sub1 ={ET_Zeroormore, RP_NA, 1, TblClassOrInterfaceTypeToInstantiate_sub1_data, 0, NULL};
TableData TblClassOrInterfaceTypeToInstantiate_sub4_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblClassOrInterfaceTypeToInstantiate_sub4 ={ET_Zeroormore, RP_NA, 1, TblClassOrInterfaceTypeToInstantiate_sub4_data, 0, NULL};
TableData TblClassOrInterfaceTypeToInstantiate_sub3_data[3] ={{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblClassOrInterfaceTypeToInstantiate_sub4},{DT_Subtable, &TblIdentifier}};
RuleTable TblClassOrInterfaceTypeToInstantiate_sub3 ={ET_Concatenate, RP_NA, 3, TblClassOrInterfaceTypeToInstantiate_sub3_data, 0, NULL};
TableData TblClassOrInterfaceTypeToInstantiate_sub2_data[1] ={{DT_Subtable, &TblClassOrInterfaceTypeToInstantiate_sub3}};
RuleTable TblClassOrInterfaceTypeToInstantiate_sub2 ={ET_Zeroormore, RP_NA, 1, TblClassOrInterfaceTypeToInstantiate_sub2_data, 0, NULL};
TableData TblClassOrInterfaceTypeToInstantiate_sub5_data[1] ={{DT_Subtable, &TblTypeArgumentsOrDiamond}};
RuleTable TblClassOrInterfaceTypeToInstantiate_sub5 ={ET_Zeroorone, RP_NA, 1, TblClassOrInterfaceTypeToInstantiate_sub5_data, 0, NULL};
TableData TblClassOrInterfaceTypeToInstantiate_data[4] ={{DT_Subtable, &TblClassOrInterfaceTypeToInstantiate_sub1},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblClassOrInterfaceTypeToInstantiate_sub2},{DT_Subtable, &TblClassOrInterfaceTypeToInstantiate_sub5}};
RuleTable TblClassOrInterfaceTypeToInstantiate ={ET_Concatenate, RP_NA, 4, TblClassOrInterfaceTypeToInstantiate_data, 0, NULL};
TableData TblTypeArgumentsOrDiamond_data[2] ={{DT_Subtable, &TblTypeArguments},{DT_String, {.mString="<>"}}};
RuleTable TblTypeArgumentsOrDiamond ={ET_Oneof, RP_NA, 2, TblTypeArgumentsOrDiamond_data, 0, NULL};
TableData TblArgumentList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblExpression}};
RuleTable TblArgumentList_sub2 ={ET_Concatenate, RP_NA, 2, TblArgumentList_sub2_data, 0, NULL};
TableData TblArgumentList_sub1_data[1] ={{DT_Subtable, &TblArgumentList_sub2}};
RuleTable TblArgumentList_sub1 ={ET_Zeroormore, RP_NA, 1, TblArgumentList_sub1_data, 0, NULL};
TableData TblArgumentList_data[2] ={{DT_Subtable, &TblExpression},{DT_Subtable, &TblArgumentList_sub1}};
RuleTable TblArgumentList ={ET_Concatenate, RP_NA, 2, TblArgumentList_data, 0, NULL};
TableData TblArrayInitializer_sub1_data[1] ={{DT_Subtable, &TblVariableInitializerList}};
RuleTable TblArrayInitializer_sub1 ={ET_Zeroorone, RP_NA, 1, TblArrayInitializer_sub1_data, 0, NULL};
TableData TblArrayInitializer_sub2_data[1] ={{DT_Token, {.mTokenId=44}}};
RuleTable TblArrayInitializer_sub2 ={ET_Zeroorone, RP_NA, 1, TblArrayInitializer_sub2_data, 0, NULL};
TableData TblArrayInitializer_data[4] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblArrayInitializer_sub1},{DT_Subtable, &TblArrayInitializer_sub2},{DT_Token, {.mTokenId=48}}};
RuleTable TblArrayInitializer ={ET_Concatenate, RP_NA, 4, TblArrayInitializer_data, 0, NULL};
TableData TblArrayCreationExpression_sub2_data[1] ={{DT_Subtable, &TblDims}};
RuleTable TblArrayCreationExpression_sub2 ={ET_Zeroorone, RP_NA, 1, TblArrayCreationExpression_sub2_data, 0, NULL};
TableData TblArrayCreationExpression_sub1_data[4] ={{DT_Token, {.mTokenId=97}},{DT_Subtable, &TblPrimitiveType},{DT_Subtable, &TblDimExprs},{DT_Subtable, &TblArrayCreationExpression_sub2}};
RuleTable TblArrayCreationExpression_sub1 ={ET_Concatenate, RP_NA, 4, TblArrayCreationExpression_sub1_data, 0, NULL};
TableData TblArrayCreationExpression_sub4_data[1] ={{DT_Subtable, &TblDims}};
RuleTable TblArrayCreationExpression_sub4 ={ET_Zeroorone, RP_NA, 1, TblArrayCreationExpression_sub4_data, 0, NULL};
TableData TblArrayCreationExpression_sub3_data[4] ={{DT_Token, {.mTokenId=97}},{DT_Subtable, &TblClassOrInterfaceType},{DT_Subtable, &TblDimExprs},{DT_Subtable, &TblArrayCreationExpression_sub4}};
RuleTable TblArrayCreationExpression_sub3 ={ET_Concatenate, RP_NA, 4, TblArrayCreationExpression_sub3_data, 0, NULL};
TableData TblArrayCreationExpression_sub5_data[4] ={{DT_Token, {.mTokenId=97}},{DT_Subtable, &TblPrimitiveType},{DT_Subtable, &TblDims},{DT_Subtable, &TblArrayInitializer}};
RuleTable TblArrayCreationExpression_sub5 ={ET_Concatenate, RP_NA, 4, TblArrayCreationExpression_sub5_data, 0, NULL};
TableData TblArrayCreationExpression_sub6_data[4] ={{DT_Token, {.mTokenId=97}},{DT_Subtable, &TblClassOrInterfaceType},{DT_Subtable, &TblDims},{DT_Subtable, &TblArrayInitializer}};
RuleTable TblArrayCreationExpression_sub6 ={ET_Concatenate, RP_NA, 4, TblArrayCreationExpression_sub6_data, 0, NULL};
TableData TblArrayCreationExpression_data[4] ={{DT_Subtable, &TblArrayCreationExpression_sub1},{DT_Subtable, &TblArrayCreationExpression_sub3},{DT_Subtable, &TblArrayCreationExpression_sub5},{DT_Subtable, &TblArrayCreationExpression_sub6}};
RuleTable TblArrayCreationExpression ={ET_Oneof, RP_NA, 4, TblArrayCreationExpression_data, 0, NULL};
TableData TblDimExprs_sub1_data[1] ={{DT_Subtable, &TblDimExpr}};
RuleTable TblDimExprs_sub1 ={ET_Zeroormore, RP_NA, 1, TblDimExprs_sub1_data, 0, NULL};
TableData TblDimExprs_data[2] ={{DT_Subtable, &TblDimExpr},{DT_Subtable, &TblDimExprs_sub1}};
RuleTable TblDimExprs ={ET_Concatenate, RP_NA, 2, TblDimExprs_data, 0, NULL};
TableData TblDimExpr_sub1_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblDimExpr_sub1 ={ET_Zeroormore, RP_NA, 1, TblDimExpr_sub1_data, 0, NULL};
TableData TblDimExpr_data[4] ={{DT_Subtable, &TblDimExpr_sub1},{DT_Token, {.mTokenId=47}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=46}}};
RuleTable TblDimExpr ={ET_Concatenate, RP_NA, 4, TblDimExpr_data, 0, NULL};
TableData TblArrayAccess_sub2_data[1] ={{DT_Subtable, &TblExpression}};
RuleTable TblArrayAccess_sub2 ={ET_Zeroorone, RP_NA, 1, TblArrayAccess_sub2_data, 0, NULL};
TableData TblArrayAccess_sub1_data[2] ={{DT_Subtable, &TblExpressionName},{DT_Subtable, &TblArrayAccess_sub2}};
RuleTable TblArrayAccess_sub1 ={ET_Concatenate, RP_NA, 2, TblArrayAccess_sub1_data, 0, NULL};
TableData TblArrayAccess_sub4_data[1] ={{DT_Subtable, &TblExpression}};
RuleTable TblArrayAccess_sub4 ={ET_Zeroorone, RP_NA, 1, TblArrayAccess_sub4_data, 0, NULL};
TableData TblArrayAccess_sub3_data[2] ={{DT_Subtable, &TblPrimaryNoNewArray},{DT_Subtable, &TblArrayAccess_sub4}};
RuleTable TblArrayAccess_sub3 ={ET_Concatenate, RP_NA, 2, TblArrayAccess_sub3_data, 0, NULL};
TableData TblArrayAccess_data[2] ={{DT_Subtable, &TblArrayAccess_sub1},{DT_Subtable, &TblArrayAccess_sub3}};
RuleTable TblArrayAccess ={ET_Oneof, RP_NA, 2, TblArrayAccess_data, 0, NULL};
TableData TblFieldAccess_sub1_data[3] ={{DT_Subtable, &TblPrimary},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblFieldAccess_sub1 ={ET_Concatenate, RP_NA, 3, TblFieldAccess_sub1_data, 0, NULL};
TableData TblFieldAccess_sub2_data[3] ={{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblFieldAccess_sub2 ={ET_Concatenate, RP_NA, 3, TblFieldAccess_sub2_data, 0, NULL};
TableData TblFieldAccess_sub3_data[5] ={{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=43}},{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblFieldAccess_sub3 ={ET_Concatenate, RP_NA, 5, TblFieldAccess_sub3_data, 0, NULL};
TableData TblFieldAccess_data[3] ={{DT_Subtable, &TblFieldAccess_sub1},{DT_Subtable, &TblFieldAccess_sub2},{DT_Subtable, &TblFieldAccess_sub3}};
RuleTable TblFieldAccess ={ET_Oneof, RP_NA, 3, TblFieldAccess_data, 0, NULL};
Action TblMethodInvocation_sub1_action[2] = {{ACT_BuildCall,1,{1}},{ACT_AddArguments,1,{3}}};
TableData TblMethodInvocation_sub2_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblMethodInvocation_sub2 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub2_data, 0, NULL};
TableData TblMethodInvocation_sub1_data[4] ={{DT_Subtable, &TblMethodName},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblMethodInvocation_sub2},{DT_Token, {.mTokenId=50}}};
RuleTable TblMethodInvocation_sub1 ={ET_Concatenate, RP_NA, 4, TblMethodInvocation_sub1_data, 2, TblMethodInvocation_sub1_action};
Action TblMethodInvocation_sub3_action[3] = {{ACT_BuildField,2,{1,4}},{ACT_BuildCall,0,{}},{ACT_AddArguments,1,{6}}};
TableData TblMethodInvocation_sub4_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodInvocation_sub4 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub4_data, 0, NULL};
TableData TblMethodInvocation_sub5_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblMethodInvocation_sub5 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub5_data, 0, NULL};
TableData TblMethodInvocation_sub3_data[7] ={{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblMethodInvocation_sub4},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblMethodInvocation_sub5},{DT_Token, {.mTokenId=50}}};
RuleTable TblMethodInvocation_sub3 ={ET_Concatenate, RP_NA, 7, TblMethodInvocation_sub3_data, 3, TblMethodInvocation_sub3_action};
TableData TblMethodInvocation_sub7_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodInvocation_sub7 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub7_data, 0, NULL};
TableData TblMethodInvocation_sub8_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblMethodInvocation_sub8 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub8_data, 0, NULL};
TableData TblMethodInvocation_sub6_data[7] ={{DT_Subtable, &TblExpressionName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblMethodInvocation_sub7},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblMethodInvocation_sub8},{DT_Token, {.mTokenId=50}}};
RuleTable TblMethodInvocation_sub6 ={ET_Concatenate, RP_NA, 7, TblMethodInvocation_sub6_data, 0, NULL};
TableData TblMethodInvocation_sub10_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodInvocation_sub10 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub10_data, 0, NULL};
TableData TblMethodInvocation_sub11_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblMethodInvocation_sub11 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub11_data, 0, NULL};
TableData TblMethodInvocation_sub9_data[7] ={{DT_Subtable, &TblPrimary},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblMethodInvocation_sub10},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblMethodInvocation_sub11},{DT_Token, {.mTokenId=50}}};
RuleTable TblMethodInvocation_sub9 ={ET_Concatenate, RP_NA, 7, TblMethodInvocation_sub9_data, 0, NULL};
TableData TblMethodInvocation_sub13_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodInvocation_sub13 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub13_data, 0, NULL};
TableData TblMethodInvocation_sub14_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblMethodInvocation_sub14 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub14_data, 0, NULL};
TableData TblMethodInvocation_sub12_data[7] ={{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblMethodInvocation_sub13},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblMethodInvocation_sub14},{DT_Token, {.mTokenId=50}}};
RuleTable TblMethodInvocation_sub12 ={ET_Concatenate, RP_NA, 7, TblMethodInvocation_sub12_data, 0, NULL};
TableData TblMethodInvocation_sub16_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodInvocation_sub16 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub16_data, 0, NULL};
TableData TblMethodInvocation_sub17_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblMethodInvocation_sub17 ={ET_Zeroorone, RP_NA, 1, TblMethodInvocation_sub17_data, 0, NULL};
TableData TblMethodInvocation_sub15_data[9] ={{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=43}},{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblMethodInvocation_sub16},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblMethodInvocation_sub17},{DT_Token, {.mTokenId=50}}};
RuleTable TblMethodInvocation_sub15 ={ET_Concatenate, RP_NA, 9, TblMethodInvocation_sub15_data, 0, NULL};
TableData TblMethodInvocation_data[6] ={{DT_Subtable, &TblMethodInvocation_sub1},{DT_Subtable, &TblMethodInvocation_sub3},{DT_Subtable, &TblMethodInvocation_sub6},{DT_Subtable, &TblMethodInvocation_sub9},{DT_Subtable, &TblMethodInvocation_sub12},{DT_Subtable, &TblMethodInvocation_sub15}};
RuleTable TblMethodInvocation ={ET_Oneof, RP_NA, 6, TblMethodInvocation_data, 0, NULL};
TableData TblMethodReference_sub2_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodReference_sub2 ={ET_Zeroorone, RP_NA, 1, TblMethodReference_sub2_data, 0, NULL};
TableData TblMethodReference_sub1_data[4] ={{DT_Subtable, &TblExpressionName},{DT_Token, {.mTokenId=39}},{DT_Subtable, &TblMethodReference_sub2},{DT_Subtable, &TblIdentifier}};
RuleTable TblMethodReference_sub1 ={ET_Concatenate, RP_NA, 4, TblMethodReference_sub1_data, 0, NULL};
TableData TblMethodReference_sub4_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodReference_sub4 ={ET_Zeroorone, RP_NA, 1, TblMethodReference_sub4_data, 0, NULL};
TableData TblMethodReference_sub3_data[4] ={{DT_Subtable, &TblPrimary},{DT_Token, {.mTokenId=39}},{DT_Subtable, &TblMethodReference_sub4},{DT_Subtable, &TblIdentifier}};
RuleTable TblMethodReference_sub3 ={ET_Concatenate, RP_NA, 4, TblMethodReference_sub3_data, 0, NULL};
TableData TblMethodReference_sub6_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodReference_sub6 ={ET_Zeroorone, RP_NA, 1, TblMethodReference_sub6_data, 0, NULL};
TableData TblMethodReference_sub5_data[4] ={{DT_Subtable, &TblReferenceType},{DT_Token, {.mTokenId=39}},{DT_Subtable, &TblMethodReference_sub6},{DT_Subtable, &TblIdentifier}};
RuleTable TblMethodReference_sub5 ={ET_Concatenate, RP_NA, 4, TblMethodReference_sub5_data, 0, NULL};
TableData TblMethodReference_sub8_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodReference_sub8 ={ET_Zeroorone, RP_NA, 1, TblMethodReference_sub8_data, 0, NULL};
TableData TblMethodReference_sub7_data[4] ={{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=39}},{DT_Subtable, &TblMethodReference_sub8},{DT_Subtable, &TblIdentifier}};
RuleTable TblMethodReference_sub7 ={ET_Concatenate, RP_NA, 4, TblMethodReference_sub7_data, 0, NULL};
TableData TblMethodReference_sub10_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodReference_sub10 ={ET_Zeroorone, RP_NA, 1, TblMethodReference_sub10_data, 0, NULL};
TableData TblMethodReference_sub9_data[6] ={{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=43}},{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=39}},{DT_Subtable, &TblMethodReference_sub10},{DT_Subtable, &TblIdentifier}};
RuleTable TblMethodReference_sub9 ={ET_Concatenate, RP_NA, 6, TblMethodReference_sub9_data, 0, NULL};
TableData TblMethodReference_sub12_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblMethodReference_sub12 ={ET_Zeroorone, RP_NA, 1, TblMethodReference_sub12_data, 0, NULL};
TableData TblMethodReference_sub11_data[3] ={{DT_Subtable, &TblClassType},{DT_Token, {.mTokenId=39}},{DT_Subtable, &TblMethodReference_sub12}};
RuleTable TblMethodReference_sub11 ={ET_Concatenate, RP_NA, 3, TblMethodReference_sub11_data, 0, NULL};
TableData TblMethodReference_sub13_data[3] ={{DT_Subtable, &TblArrayType},{DT_Token, {.mTokenId=39}},{DT_Token, {.mTokenId=97}}};
RuleTable TblMethodReference_sub13 ={ET_Concatenate, RP_NA, 3, TblMethodReference_sub13_data, 0, NULL};
TableData TblMethodReference_data[8] ={{DT_Subtable, &TblMethodReference_sub1},{DT_Subtable, &TblMethodReference_sub3},{DT_Subtable, &TblMethodReference_sub5},{DT_Subtable, &TblMethodReference_sub7},{DT_Subtable, &TblMethodReference_sub9},{DT_Subtable, &TblMethodReference_sub11},{DT_Token, {.mTokenId=97}},{DT_Subtable, &TblMethodReference_sub13}};
RuleTable TblMethodReference ={ET_Oneof, RP_NA, 8, TblMethodReference_data, 0, NULL};
TableData TblPostfixExpression_data[4] ={{DT_Subtable, &TblPrimary},{DT_Subtable, &TblExpressionName},{DT_Subtable, &TblPostIncrementExpression},{DT_Subtable, &TblPostDecrementExpression}};
RuleTable TblPostfixExpression ={ET_Oneof, RP_NA, 4, TblPostfixExpression_data, 0, NULL};
Action TblPostIncrementExpression_action[1] = {{ACT_BuildPostfixOperation,2,{2,1}}};
TableData TblPostIncrementExpression_data[2] ={{DT_Subtable, &TblPostfixExpression},{DT_Token, {.mTokenId=22}}};
RuleTable TblPostIncrementExpression ={ET_Concatenate, RP_NA, 2, TblPostIncrementExpression_data, 1, TblPostIncrementExpression_action};
Action TblPostDecrementExpression_action[1] = {{ACT_BuildPostfixOperation,2,{2,1}}};
TableData TblPostDecrementExpression_data[2] ={{DT_Subtable, &TblPostfixExpression},{DT_Token, {.mTokenId=21}}};
RuleTable TblPostDecrementExpression ={ET_Concatenate, RP_NA, 2, TblPostDecrementExpression_data, 1, TblPostDecrementExpression_action};
Action TblUnaryExpression_sub1_action[1] = {{ACT_BuildUnaryOperation,2,{1,2}}};
TableData TblUnaryExpression_sub1_data[2] ={{DT_Token, {.mTokenId=37}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblUnaryExpression_sub1 ={ET_Concatenate, RP_NA, 2, TblUnaryExpression_sub1_data, 1, TblUnaryExpression_sub1_action};
Action TblUnaryExpression_sub2_action[1] = {{ACT_BuildUnaryOperation,2,{1,2}}};
TableData TblUnaryExpression_sub2_data[2] ={{DT_Token, {.mTokenId=36}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblUnaryExpression_sub2 ={ET_Concatenate, RP_NA, 2, TblUnaryExpression_sub2_data, 1, TblUnaryExpression_sub2_action};
TableData TblUnaryExpression_data[5] ={{DT_Subtable, &TblPreIncrementExpression},{DT_Subtable, &TblPreDecrementExpression},{DT_Subtable, &TblUnaryExpression_sub1},{DT_Subtable, &TblUnaryExpression_sub2},{DT_Subtable, &TblUnaryExpressionNotPlusMinus}};
RuleTable TblUnaryExpression ={ET_Oneof, RP_NA, 5, TblUnaryExpression_data, 0, NULL};
Action TblPreIncrementExpression_action[1] = {{ACT_BuildUnaryOperation,2,{1,2}}};
TableData TblPreIncrementExpression_data[2] ={{DT_Token, {.mTokenId=22}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblPreIncrementExpression ={ET_Concatenate, RP_NA, 2, TblPreIncrementExpression_data, 1, TblPreIncrementExpression_action};
Action TblPreDecrementExpression_action[1] = {{ACT_BuildUnaryOperation,2,{1,2}}};
TableData TblPreDecrementExpression_data[2] ={{DT_Token, {.mTokenId=21}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblPreDecrementExpression ={ET_Concatenate, RP_NA, 2, TblPreDecrementExpression_data, 1, TblPreDecrementExpression_action};
TableData TblUnaryExpressionNotPlusMinus_sub1_data[2] ={{DT_Token, {.mTokenId=27}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblUnaryExpressionNotPlusMinus_sub1 ={ET_Concatenate, RP_NA, 2, TblUnaryExpressionNotPlusMinus_sub1_data, 0, NULL};
TableData TblUnaryExpressionNotPlusMinus_sub2_data[2] ={{DT_Token, {.mTokenId=26}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblUnaryExpressionNotPlusMinus_sub2 ={ET_Concatenate, RP_NA, 2, TblUnaryExpressionNotPlusMinus_sub2_data, 0, NULL};
TableData TblUnaryExpressionNotPlusMinus_data[4] ={{DT_Subtable, &TblPostfixExpression},{DT_Subtable, &TblUnaryExpressionNotPlusMinus_sub1},{DT_Subtable, &TblUnaryExpressionNotPlusMinus_sub2},{DT_Subtable, &TblCastExpression}};
RuleTable TblUnaryExpressionNotPlusMinus ={ET_Oneof, RP_NA, 4, TblUnaryExpressionNotPlusMinus_data, 0, NULL};
Action TblCastExpression_sub1_action[1] = {{ACT_BuildCast,2,{2,4}}};
TableData TblCastExpression_sub1_data[4] ={{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblPrimitiveType},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblCastExpression_sub1 ={ET_Concatenate, RP_NA, 4, TblCastExpression_sub1_data, 1, TblCastExpression_sub1_action};
Action TblCastExpression_sub2_action[1] = {{ACT_BuildCast,2,{2,5}}};
TableData TblCastExpression_sub3_data[1] ={{DT_Subtable, &TblAdditionalBound}};
RuleTable TblCastExpression_sub3 ={ET_Zeroormore, RP_NA, 1, TblCastExpression_sub3_data, 0, NULL};
TableData TblCastExpression_sub2_data[5] ={{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblReferenceType},{DT_Subtable, &TblCastExpression_sub3},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblUnaryExpressionNotPlusMinus}};
RuleTable TblCastExpression_sub2 ={ET_Concatenate, RP_NA, 5, TblCastExpression_sub2_data, 1, TblCastExpression_sub2_action};
Action TblCastExpression_sub4_action[1] = {{ACT_BuildCast,2,{2,5}}};
TableData TblCastExpression_sub5_data[1] ={{DT_Subtable, &TblAdditionalBound}};
RuleTable TblCastExpression_sub5 ={ET_Zeroormore, RP_NA, 1, TblCastExpression_sub5_data, 0, NULL};
TableData TblCastExpression_sub4_data[5] ={{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblReferenceType},{DT_Subtable, &TblCastExpression_sub5},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblLambdaExpression}};
RuleTable TblCastExpression_sub4 ={ET_Concatenate, RP_NA, 5, TblCastExpression_sub4_data, 1, TblCastExpression_sub4_action};
TableData TblCastExpression_data[3] ={{DT_Subtable, &TblCastExpression_sub1},{DT_Subtable, &TblCastExpression_sub2},{DT_Subtable, &TblCastExpression_sub4}};
RuleTable TblCastExpression ={ET_Oneof, RP_NA, 3, TblCastExpression_data, 0, NULL};
TableData TblMultiplicativeExpression_sub1_data[3] ={{DT_Subtable, &TblMultiplicativeExpression},{DT_Token, {.mTokenId=35}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblMultiplicativeExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblMultiplicativeExpression_sub1_data, 0, NULL};
TableData TblMultiplicativeExpression_sub2_data[3] ={{DT_Subtable, &TblMultiplicativeExpression},{DT_Token, {.mTokenId=34}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblMultiplicativeExpression_sub2 ={ET_Concatenate, RP_NA, 3, TblMultiplicativeExpression_sub2_data, 0, NULL};
TableData TblMultiplicativeExpression_sub3_data[3] ={{DT_Subtable, &TblMultiplicativeExpression},{DT_Token, {.mTokenId=33}},{DT_Subtable, &TblUnaryExpression}};
RuleTable TblMultiplicativeExpression_sub3 ={ET_Concatenate, RP_NA, 3, TblMultiplicativeExpression_sub3_data, 0, NULL};
TableData TblMultiplicativeExpression_data[4] ={{DT_Subtable, &TblUnaryExpression},{DT_Subtable, &TblMultiplicativeExpression_sub1},{DT_Subtable, &TblMultiplicativeExpression_sub2},{DT_Subtable, &TblMultiplicativeExpression_sub3}};
RuleTable TblMultiplicativeExpression ={ET_Oneof, RP_NA, 4, TblMultiplicativeExpression_data, 0, NULL};
Action TblAdditiveExpression_sub1_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblAdditiveExpression_sub1_data[3] ={{DT_Subtable, &TblAdditiveExpression},{DT_Token, {.mTokenId=37}},{DT_Subtable, &TblMultiplicativeExpression}};
RuleTable TblAdditiveExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblAdditiveExpression_sub1_data, 1, TblAdditiveExpression_sub1_action};
Action TblAdditiveExpression_sub2_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblAdditiveExpression_sub2_data[3] ={{DT_Subtable, &TblAdditiveExpression},{DT_Token, {.mTokenId=36}},{DT_Subtable, &TblMultiplicativeExpression}};
RuleTable TblAdditiveExpression_sub2 ={ET_Concatenate, RP_NA, 3, TblAdditiveExpression_sub2_data, 1, TblAdditiveExpression_sub2_action};
TableData TblAdditiveExpression_data[3] ={{DT_Subtable, &TblMultiplicativeExpression},{DT_Subtable, &TblAdditiveExpression_sub1},{DT_Subtable, &TblAdditiveExpression_sub2}};
RuleTable TblAdditiveExpression ={ET_Oneof, RP_NA, 3, TblAdditiveExpression_data, 0, NULL};
Action TblShiftExpression_sub1_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblShiftExpression_sub1_data[3] ={{DT_Subtable, &TblShiftExpression},{DT_Token, {.mTokenId=16}},{DT_Subtable, &TblAdditiveExpression}};
RuleTable TblShiftExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblShiftExpression_sub1_data, 1, TblShiftExpression_sub1_action};
Action TblShiftExpression_sub2_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblShiftExpression_sub2_data[3] ={{DT_Subtable, &TblShiftExpression},{DT_Token, {.mTokenId=15}},{DT_Subtable, &TblAdditiveExpression}};
RuleTable TblShiftExpression_sub2 ={ET_Concatenate, RP_NA, 3, TblShiftExpression_sub2_data, 1, TblShiftExpression_sub2_action};
Action TblShiftExpression_sub3_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblShiftExpression_sub3_data[3] ={{DT_Subtable, &TblShiftExpression},{DT_Token, {.mTokenId=3}},{DT_Subtable, &TblAdditiveExpression}};
RuleTable TblShiftExpression_sub3 ={ET_Concatenate, RP_NA, 3, TblShiftExpression_sub3_data, 1, TblShiftExpression_sub3_action};
TableData TblShiftExpression_data[4] ={{DT_Subtable, &TblAdditiveExpression},{DT_Subtable, &TblShiftExpression_sub1},{DT_Subtable, &TblShiftExpression_sub2},{DT_Subtable, &TblShiftExpression_sub3}};
RuleTable TblShiftExpression ={ET_Oneof, RP_NA, 4, TblShiftExpression_data, 0, NULL};
Action TblRelationalExpression_sub1_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblRelationalExpression_sub1_data[3] ={{DT_Subtable, &TblRelationalExpression},{DT_Token, {.mTokenId=31}},{DT_Subtable, &TblShiftExpression}};
RuleTable TblRelationalExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblRelationalExpression_sub1_data, 1, TblRelationalExpression_sub1_action};
Action TblRelationalExpression_sub2_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblRelationalExpression_sub2_data[3] ={{DT_Subtable, &TblRelationalExpression},{DT_Token, {.mTokenId=32}},{DT_Subtable, &TblShiftExpression}};
RuleTable TblRelationalExpression_sub2 ={ET_Concatenate, RP_NA, 3, TblRelationalExpression_sub2_data, 1, TblRelationalExpression_sub2_action};
Action TblRelationalExpression_sub3_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblRelationalExpression_sub3_data[3] ={{DT_Subtable, &TblRelationalExpression},{DT_Token, {.mTokenId=17}},{DT_Subtable, &TblShiftExpression}};
RuleTable TblRelationalExpression_sub3 ={ET_Concatenate, RP_NA, 3, TblRelationalExpression_sub3_data, 1, TblRelationalExpression_sub3_action};
Action TblRelationalExpression_sub4_action[1] = {{ACT_BuildBinaryOperation,3,{1,2,3}}};
TableData TblRelationalExpression_sub4_data[3] ={{DT_Subtable, &TblRelationalExpression},{DT_Token, {.mTokenId=18}},{DT_Subtable, &TblShiftExpression}};
RuleTable TblRelationalExpression_sub4 ={ET_Concatenate, RP_NA, 3, TblRelationalExpression_sub4_data, 1, TblRelationalExpression_sub4_action};
TableData TblRelationalExpression_sub5_data[3] ={{DT_Subtable, &TblRelationalExpression},{DT_Token, {.mTokenId=55}},{DT_Subtable, &TblReferenceType}};
RuleTable TblRelationalExpression_sub5 ={ET_Concatenate, RP_NA, 3, TblRelationalExpression_sub5_data, 0, NULL};
TableData TblRelationalExpression_data[6] ={{DT_Subtable, &TblShiftExpression},{DT_Subtable, &TblRelationalExpression_sub1},{DT_Subtable, &TblRelationalExpression_sub2},{DT_Subtable, &TblRelationalExpression_sub3},{DT_Subtable, &TblRelationalExpression_sub4},{DT_Subtable, &TblRelationalExpression_sub5}};
RuleTable TblRelationalExpression ={ET_Oneof, RP_NA, 6, TblRelationalExpression_data, 0, NULL};
TableData TblEqualityExpression_sub1_data[3] ={{DT_Subtable, &TblEqualityExpression},{DT_Token, {.mTokenId=20}},{DT_Subtable, &TblRelationalExpression}};
RuleTable TblEqualityExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblEqualityExpression_sub1_data, 0, NULL};
TableData TblEqualityExpression_sub2_data[3] ={{DT_Subtable, &TblEqualityExpression},{DT_Token, {.mTokenId=19}},{DT_Subtable, &TblRelationalExpression}};
RuleTable TblEqualityExpression_sub2 ={ET_Concatenate, RP_NA, 3, TblEqualityExpression_sub2_data, 0, NULL};
TableData TblEqualityExpression_data[3] ={{DT_Subtable, &TblRelationalExpression},{DT_Subtable, &TblEqualityExpression_sub1},{DT_Subtable, &TblEqualityExpression_sub2}};
RuleTable TblEqualityExpression ={ET_Oneof, RP_NA, 3, TblEqualityExpression_data, 0, NULL};
TableData TblAndExpression_sub1_data[3] ={{DT_Subtable, &TblAndExpression},{DT_Token, {.mTokenId=30}},{DT_Subtable, &TblEqualityExpression}};
RuleTable TblAndExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblAndExpression_sub1_data, 0, NULL};
TableData TblAndExpression_data[2] ={{DT_Subtable, &TblEqualityExpression},{DT_Subtable, &TblAndExpression_sub1}};
RuleTable TblAndExpression ={ET_Oneof, RP_NA, 2, TblAndExpression_data, 0, NULL};
TableData TblExclusiveOrExpression_sub1_data[3] ={{DT_Subtable, &TblExclusiveOrExpression},{DT_Token, {.mTokenId=28}},{DT_Subtable, &TblAndExpression}};
RuleTable TblExclusiveOrExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblExclusiveOrExpression_sub1_data, 0, NULL};
TableData TblExclusiveOrExpression_data[2] ={{DT_Subtable, &TblAndExpression},{DT_Subtable, &TblExclusiveOrExpression_sub1}};
RuleTable TblExclusiveOrExpression ={ET_Oneof, RP_NA, 2, TblExclusiveOrExpression_data, 0, NULL};
TableData TblInclusiveOrExpression_sub1_data[3] ={{DT_Subtable, &TblInclusiveOrExpression},{DT_Token, {.mTokenId=29}},{DT_Subtable, &TblExclusiveOrExpression}};
RuleTable TblInclusiveOrExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblInclusiveOrExpression_sub1_data, 0, NULL};
TableData TblInclusiveOrExpression_data[2] ={{DT_Subtable, &TblExclusiveOrExpression},{DT_Subtable, &TblInclusiveOrExpression_sub1}};
RuleTable TblInclusiveOrExpression ={ET_Oneof, RP_NA, 2, TblInclusiveOrExpression_data, 0, NULL};
TableData TblConditionalAndExpression_sub1_data[3] ={{DT_Subtable, &TblConditionalAndExpression},{DT_Token, {.mTokenId=14}},{DT_Subtable, &TblInclusiveOrExpression}};
RuleTable TblConditionalAndExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblConditionalAndExpression_sub1_data, 0, NULL};
TableData TblConditionalAndExpression_data[2] ={{DT_Subtable, &TblInclusiveOrExpression},{DT_Subtable, &TblConditionalAndExpression_sub1}};
RuleTable TblConditionalAndExpression ={ET_Oneof, RP_NA, 2, TblConditionalAndExpression_data, 0, NULL};
TableData TblConditionalOrExpression_sub1_data[3] ={{DT_Subtable, &TblConditionalOrExpression},{DT_Token, {.mTokenId=13}},{DT_Subtable, &TblConditionalAndExpression}};
RuleTable TblConditionalOrExpression_sub1 ={ET_Concatenate, RP_NA, 3, TblConditionalOrExpression_sub1_data, 0, NULL};
TableData TblConditionalOrExpression_data[2] ={{DT_Subtable, &TblConditionalAndExpression},{DT_Subtable, &TblConditionalOrExpression_sub1}};
RuleTable TblConditionalOrExpression ={ET_Oneof, RP_NA, 2, TblConditionalOrExpression_data, 0, NULL};
TableData TblConditionalExpression_sub1_data[5] ={{DT_Subtable, &TblConditionalOrExpression},{DT_Token, {.mTokenId=23}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=24}},{DT_Subtable, &TblConditionalExpression}};
RuleTable TblConditionalExpression_sub1 ={ET_Concatenate, RP_NA, 5, TblConditionalExpression_sub1_data, 0, NULL};
TableData TblConditionalExpression_sub2_data[5] ={{DT_Subtable, &TblConditionalOrExpression},{DT_Token, {.mTokenId=23}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=24}},{DT_Subtable, &TblLambdaExpression}};
RuleTable TblConditionalExpression_sub2 ={ET_Concatenate, RP_NA, 5, TblConditionalExpression_sub2_data, 0, NULL};
TableData TblConditionalExpression_data[3] ={{DT_Subtable, &TblConditionalOrExpression},{DT_Subtable, &TblConditionalExpression_sub1},{DT_Subtable, &TblConditionalExpression_sub2}};
RuleTable TblConditionalExpression ={ET_Oneof, RP_NA, 3, TblConditionalExpression_data, 0, NULL};
TableData TblAssignmentExpression_data[2] ={{DT_Subtable, &TblConditionalExpression},{DT_Subtable, &TblAssignment}};
RuleTable TblAssignmentExpression ={ET_Oneof, RP_NA, 2, TblAssignmentExpression_data, 0, NULL};
Action TblAssignment_action[1] = {{ACT_BuildAssignment,3,{1,2,3}}};
TableData TblAssignment_data[3] ={{DT_Subtable, &TblLeftHandSide},{DT_Subtable, &TblAssignmentOperator},{DT_Subtable, &TblExpression}};
RuleTable TblAssignment ={ET_Concatenate, RP_NA, 3, TblAssignment_data, 1, TblAssignment_action};
TableData TblLeftHandSide_data[3] ={{DT_Subtable, &TblExpressionName},{DT_Subtable, &TblFieldAccess},{DT_Subtable, &TblArrayAccess}};
RuleTable TblLeftHandSide ={ET_Oneof, RP_NA, 3, TblLeftHandSide_data, 0, NULL};
TableData TblAssignmentOperator_data[12] ={{DT_Token, {.mTokenId=25}},{DT_Token, {.mTokenId=10}},{DT_Token, {.mTokenId=9}},{DT_Token, {.mTokenId=8}},{DT_Token, {.mTokenId=12}},{DT_Token, {.mTokenId=11}},{DT_Token, {.mTokenId=2}},{DT_Token, {.mTokenId=1}},{DT_Token, {.mTokenId=0}},{DT_Token, {.mTokenId=7}},{DT_Token, {.mTokenId=5}},{DT_Token, {.mTokenId=6}}};
RuleTable TblAssignmentOperator ={ET_Oneof, RP_NA, 12, TblAssignmentOperator_data, 0, NULL};
TableData TblLambdaExpression_data[3] ={{DT_Subtable, &TblLambdaParameters},{DT_Token, {.mTokenId=4}},{DT_Subtable, &TblLambdaBody}};
RuleTable TblLambdaExpression ={ET_Concatenate, RP_NA, 3, TblLambdaExpression_data, 0, NULL};
TableData TblLambdaParameters_sub2_data[1] ={{DT_Subtable, &TblLambdaParameterList}};
RuleTable TblLambdaParameters_sub2 ={ET_Zeroorone, RP_NA, 1, TblLambdaParameters_sub2_data, 0, NULL};
TableData TblLambdaParameters_sub1_data[3] ={{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblLambdaParameters_sub2},{DT_Token, {.mTokenId=50}}};
RuleTable TblLambdaParameters_sub1 ={ET_Concatenate, RP_NA, 3, TblLambdaParameters_sub1_data, 0, NULL};
TableData TblLambdaParameters_data[2] ={{DT_Subtable, &TblLambdaParameters_sub1},{DT_Subtable, &TblIdentifier}};
RuleTable TblLambdaParameters ={ET_Oneof, RP_NA, 2, TblLambdaParameters_data, 0, NULL};
TableData TblLambdaParameterList_sub3_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblLambdaParameter}};
RuleTable TblLambdaParameterList_sub3 ={ET_Concatenate, RP_NA, 2, TblLambdaParameterList_sub3_data, 0, NULL};
TableData TblLambdaParameterList_sub2_data[1] ={{DT_Subtable, &TblLambdaParameterList_sub3}};
RuleTable TblLambdaParameterList_sub2 ={ET_Zeroormore, RP_NA, 1, TblLambdaParameterList_sub2_data, 0, NULL};
TableData TblLambdaParameterList_sub1_data[2] ={{DT_Subtable, &TblLambdaParameter},{DT_Subtable, &TblLambdaParameterList_sub2}};
RuleTable TblLambdaParameterList_sub1 ={ET_Concatenate, RP_NA, 2, TblLambdaParameterList_sub1_data, 0, NULL};
TableData TblLambdaParameterList_sub6_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblIdentifier}};
RuleTable TblLambdaParameterList_sub6 ={ET_Concatenate, RP_NA, 2, TblLambdaParameterList_sub6_data, 0, NULL};
TableData TblLambdaParameterList_sub5_data[1] ={{DT_Subtable, &TblLambdaParameterList_sub6}};
RuleTable TblLambdaParameterList_sub5 ={ET_Zeroormore, RP_NA, 1, TblLambdaParameterList_sub5_data, 0, NULL};
TableData TblLambdaParameterList_sub4_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblLambdaParameterList_sub5}};
RuleTable TblLambdaParameterList_sub4 ={ET_Concatenate, RP_NA, 2, TblLambdaParameterList_sub4_data, 0, NULL};
TableData TblLambdaParameterList_data[2] ={{DT_Subtable, &TblLambdaParameterList_sub1},{DT_Subtable, &TblLambdaParameterList_sub4}};
RuleTable TblLambdaParameterList ={ET_Oneof, RP_NA, 2, TblLambdaParameterList_data, 0, NULL};
TableData TblLambdaParameter_sub2_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblLambdaParameter_sub2 ={ET_Zeroormore, RP_NA, 1, TblLambdaParameter_sub2_data, 0, NULL};
TableData TblLambdaParameter_sub1_data[3] ={{DT_Subtable, &TblLambdaParameter_sub2},{DT_Subtable, &TblLambdaParameterType},{DT_Subtable, &TblVariableDeclaratorId}};
RuleTable TblLambdaParameter_sub1 ={ET_Concatenate, RP_NA, 3, TblLambdaParameter_sub1_data, 0, NULL};
TableData TblLambdaParameter_data[2] ={{DT_Subtable, &TblLambdaParameter_sub1},{DT_Subtable, &TblVariableArityParameter}};
RuleTable TblLambdaParameter ={ET_Oneof, RP_NA, 2, TblLambdaParameter_data, 0, NULL};
TableData TblLambdaParameterType_data[2] ={{DT_Subtable, &TblUnannType},{DT_Token, {.mTokenId=100}}};
RuleTable TblLambdaParameterType ={ET_Oneof, RP_NA, 2, TblLambdaParameterType_data, 0, NULL};
TableData TblVariableArityParameter_sub1_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblVariableArityParameter_sub1 ={ET_Zeroormore, RP_NA, 1, TblVariableArityParameter_sub1_data, 0, NULL};
TableData TblVariableArityParameter_sub2_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblVariableArityParameter_sub2 ={ET_Zeroormore, RP_NA, 1, TblVariableArityParameter_sub2_data, 0, NULL};
TableData TblVariableArityParameter_data[5] ={{DT_Subtable, &TblVariableArityParameter_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblVariableArityParameter_sub2},{DT_Token, {.mTokenId=38}},{DT_Subtable, &TblIdentifier}};
RuleTable TblVariableArityParameter ={ET_Concatenate, RP_NA, 5, TblVariableArityParameter_data, 0, NULL};
TableData TblLambdaBody_data[2] ={{DT_Subtable, &TblExpression},{DT_Subtable, &TblBlock}};
RuleTable TblLambdaBody ={ET_Oneof, RP_NA, 2, TblLambdaBody_data, 0, NULL};
TableData TblConstantExpression_data[1] ={{DT_Subtable, &TblExpression}};
RuleTable TblConstantExpression ={ET_Data, RP_NA, 1, TblConstantExpression_data, 0, NULL};
TableData TblPrimary_data[2] ={{DT_Subtable, &TblPrimaryNoNewArray},{DT_Subtable, &TblArrayCreationExpression}};
RuleTable TblPrimary ={ET_Oneof, RP_NA, 2, TblPrimary_data, 0, NULL};
TableData TblExpression_data[7] ={{DT_Subtable, &TblExpressionName},{DT_Subtable, &TblPrimary},{DT_Subtable, &TblUnaryExpression},{DT_Subtable, &TblBinaryExpression},{DT_Subtable, &TblConditionalExpression},{DT_Subtable, &TblLambdaExpression},{DT_Subtable, &TblAssignmentExpression}};
RuleTable TblExpression ={ET_Oneof, RP_NA, 7, TblExpression_data, 0, NULL};
TableData TblBinaryExpression_data[10] ={{DT_Subtable, &TblMultiplicativeExpression},{DT_Subtable, &TblAdditiveExpression},{DT_Subtable, &TblShiftExpression},{DT_Subtable, &TblRelationalExpression},{DT_Subtable, &TblEqualityExpression},{DT_Subtable, &TblAndExpression},{DT_Subtable, &TblExclusiveOrExpression},{DT_Subtable, &TblInclusiveOrExpression},{DT_Subtable, &TblConditionalAndExpression},{DT_Subtable, &TblConditionalOrExpression}};
RuleTable TblBinaryExpression ={ET_Oneof, RP_NA, 10, TblBinaryExpression_data, 0, NULL};
