#include "common_header_autogen.h"
TableData TblLocalVariableDeclarationStatement_data[2] ={{DT_Subtable, &TblLocalVariableDeclaration},{DT_Token, {.mTokenId=45}}};
RuleTable TblLocalVariableDeclarationStatement ={ET_Concatenate, RP_NA, 2, TblLocalVariableDeclarationStatement_data, 0, NULL};
Action TblLocalVariableDeclaration_action[2] = {{ACT_BuildDecl,2,{2,3}},{ACT_AddModifier,1,{1}}};
TableData TblLocalVariableDeclaration_sub1_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblLocalVariableDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblLocalVariableDeclaration_sub1_data, 0, NULL};
TableData TblLocalVariableDeclaration_data[3] ={{DT_Subtable, &TblLocalVariableDeclaration_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblVariableDeclaratorList}};
RuleTable TblLocalVariableDeclaration ={ET_Concatenate, RP_NA, 3, TblLocalVariableDeclaration_data, 2, TblLocalVariableDeclaration_action};
TableData TblVariableModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Token, {.mTokenId=78}}};
RuleTable TblVariableModifier ={ET_Oneof, RP_NA, 2, TblVariableModifier_data, 0, NULL};
Action TblVariableDeclaratorList_action[1] = {{ACT_BuildVarList,2,{1,2}}};
TableData TblVariableDeclaratorList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblVariableDeclarator}};
RuleTable TblVariableDeclaratorList_sub2 ={ET_Concatenate, RP_NA, 2, TblVariableDeclaratorList_sub2_data, 0, NULL};
TableData TblVariableDeclaratorList_sub1_data[1] ={{DT_Subtable, &TblVariableDeclaratorList_sub2}};
RuleTable TblVariableDeclaratorList_sub1 ={ET_Zeroormore, RP_NA, 1, TblVariableDeclaratorList_sub1_data, 0, NULL};
TableData TblVariableDeclaratorList_data[2] ={{DT_Subtable, &TblVariableDeclarator},{DT_Subtable, &TblVariableDeclaratorList_sub1}};
RuleTable TblVariableDeclaratorList ={ET_Concatenate, RP_NA, 2, TblVariableDeclaratorList_data, 1, TblVariableDeclaratorList_action};
Action TblVariableDeclarator_action[1] = {{ACT_AddInitTo,2,{1,2}}};
TableData TblVariableDeclarator_sub2_data[2] ={{DT_Token, {.mTokenId=25}},{DT_Subtable, &TblVariableInitializer}};
RuleTable TblVariableDeclarator_sub2 ={ET_Concatenate, RP_NA, 2, TblVariableDeclarator_sub2_data, 0, NULL};
TableData TblVariableDeclarator_sub1_data[1] ={{DT_Subtable, &TblVariableDeclarator_sub2}};
RuleTable TblVariableDeclarator_sub1 ={ET_Zeroorone, RP_NA, 1, TblVariableDeclarator_sub1_data, 0, NULL};
TableData TblVariableDeclarator_data[2] ={{DT_Subtable, &TblVariableDeclaratorId},{DT_Subtable, &TblVariableDeclarator_sub1}};
RuleTable TblVariableDeclarator ={ET_Concatenate, RP_NA, 2, TblVariableDeclarator_data, 1, TblVariableDeclarator_action};
Action TblVariableDeclaratorId_action[1] = {{ACT_AddDimsTo,2,{1,2}}};
TableData TblVariableDeclaratorId_sub1_data[1] ={{DT_Subtable, &TblDims}};
RuleTable TblVariableDeclaratorId_sub1 ={ET_Zeroorone, RP_NA, 1, TblVariableDeclaratorId_sub1_data, 0, NULL};
TableData TblVariableDeclaratorId_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblVariableDeclaratorId_sub1}};
RuleTable TblVariableDeclaratorId ={ET_Concatenate, RP_NA, 2, TblVariableDeclaratorId_data, 1, TblVariableDeclaratorId_action};
Action TblDims_action[1] = {{ACT_BuildDims,2,{1,2}}};
TableData TblDims_sub1_data[1] ={{DT_Subtable, &TblDim}};
RuleTable TblDims_sub1 ={ET_Zeroormore, RP_NA, 1, TblDims_sub1_data, 0, NULL};
TableData TblDims_data[2] ={{DT_Subtable, &TblDim},{DT_Subtable, &TblDims_sub1}};
RuleTable TblDims ={ET_Concatenate, RP_NA, 2, TblDims_data, 1, TblDims_action};
Action TblDim_action[1] = {{ACT_BuildDim,1,{1}}};
TableData TblDim_sub1_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblDim_sub1 ={ET_Zeroormore, RP_NA, 1, TblDim_sub1_data, 0, NULL};
TableData TblDim_data[3] ={{DT_Subtable, &TblDim_sub1},{DT_Token, {.mTokenId=47}},{DT_Token, {.mTokenId=46}}};
RuleTable TblDim ={ET_Concatenate, RP_NA, 3, TblDim_data, 1, TblDim_action};
TableData TblVariableInitializer_data[2] ={{DT_Subtable, &TblExpression},{DT_Subtable, &TblArrayInitializer}};
RuleTable TblVariableInitializer ={ET_Oneof, RP_NA, 2, TblVariableInitializer_data, 0, NULL};
TableData TblVariableInitializerList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblVariableInitializer}};
RuleTable TblVariableInitializerList_sub2 ={ET_Concatenate, RP_NA, 2, TblVariableInitializerList_sub2_data, 0, NULL};
TableData TblVariableInitializerList_sub1_data[1] ={{DT_Subtable, &TblVariableInitializerList_sub2}};
RuleTable TblVariableInitializerList_sub1 ={ET_Zeroormore, RP_NA, 1, TblVariableInitializerList_sub1_data, 0, NULL};
TableData TblVariableInitializerList_data[2] ={{DT_Subtable, &TblVariableInitializer},{DT_Subtable, &TblVariableInitializerList_sub1}};
RuleTable TblVariableInitializerList ={ET_Concatenate, RP_NA, 2, TblVariableInitializerList_data, 0, NULL};
TableData TblStatement_data[7] ={{DT_Subtable, &TblLocalVariableDeclarationStatement},{DT_Subtable, &TblStatementWithoutTrailingSubstatement},{DT_Subtable, &TblLabeledStatement},{DT_Subtable, &TblIfThenElseStatement},{DT_Subtable, &TblIfThenStatement},{DT_Subtable, &TblWhileStatement},{DT_Subtable, &TblForStatement}};
RuleTable TblStatement ={ET_Oneof, RP_Single, 7, TblStatement_data, 0, NULL};
TableData TblStatementNoShortIf_data[5] ={{DT_Subtable, &TblStatementWithoutTrailingSubstatement},{DT_Subtable, &TblLabeledStatementNoShortIf},{DT_Subtable, &TblIfThenElseStatementNoShortIf},{DT_Subtable, &TblWhileStatementNoShortIf},{DT_Subtable, &TblForStatementNoShortIf}};
RuleTable TblStatementNoShortIf ={ET_Oneof, RP_Single, 5, TblStatementNoShortIf_data, 0, NULL};
TableData TblStatementWithoutTrailingSubstatement_data[12] ={{DT_Subtable, &TblBlock},{DT_Subtable, &TblEmptyStatement},{DT_Subtable, &TblExpressionStatement},{DT_Subtable, &TblAssertStatement},{DT_Subtable, &TblSwitchStatement},{DT_Subtable, &TblDoStatement},{DT_Subtable, &TblBreakStatement},{DT_Subtable, &TblContinueStatement},{DT_Subtable, &TblReturnStatement},{DT_Subtable, &TblSynchronizedStatement},{DT_Subtable, &TblThrowStatement},{DT_Subtable, &TblTryStatement}};
RuleTable TblStatementWithoutTrailingSubstatement ={ET_Oneof, RP_Single, 12, TblStatementWithoutTrailingSubstatement_data, 0, NULL};
Action TblIfThenStatement_action[2] = {{ACT_BuildCondBranch,1,{3}},{ACT_AddCondBranchTrueStatement,1,{5}}};
TableData TblIfThenStatement_data[5] ={{DT_Token, {.mTokenId=102}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatement}};
RuleTable TblIfThenStatement ={ET_Concatenate, RP_NA, 5, TblIfThenStatement_data, 2, TblIfThenStatement_action};
Action TblIfThenElseStatement_action[3] = {{ACT_BuildCondBranch,1,{3}},{ACT_AddCondBranchTrueStatement,1,{5}},{ACT_AddCondBranchFalseStatement,1,{7}}};
TableData TblIfThenElseStatement_data[7] ={{DT_Token, {.mTokenId=102}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatementNoShortIf},{DT_Token, {.mTokenId=90}},{DT_Subtable, &TblStatement}};
RuleTable TblIfThenElseStatement ={ET_Concatenate, RP_NA, 7, TblIfThenElseStatement_data, 3, TblIfThenElseStatement_action};
Action TblIfThenElseStatementNoShortIf_action[3] = {{ACT_BuildCondBranch,1,{3}},{ACT_AddCondBranchTrueStatement,1,{5}},{ACT_AddCondBranchFalseStatement,1,{7}}};
TableData TblIfThenElseStatementNoShortIf_data[7] ={{DT_Token, {.mTokenId=102}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatementNoShortIf},{DT_Token, {.mTokenId=90}},{DT_Subtable, &TblStatementNoShortIf}};
RuleTable TblIfThenElseStatementNoShortIf ={ET_Concatenate, RP_NA, 7, TblIfThenElseStatementNoShortIf_data, 3, TblIfThenElseStatementNoShortIf_action};
TableData TblEmptyStatement_data[1] ={{DT_Token, {.mTokenId=45}}};
RuleTable TblEmptyStatement ={ET_Data, RP_NA, 1, TblEmptyStatement_data, 0, NULL};
Action TblLabeledStatement_action[1] = {{ACT_AddLabel,2,{3,1}}};
TableData TblLabeledStatement_data[3] ={{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=24}},{DT_Subtable, &TblStatement}};
RuleTable TblLabeledStatement ={ET_Concatenate, RP_NA, 3, TblLabeledStatement_data, 1, TblLabeledStatement_action};
Action TblLabeledStatementNoShortIf_action[1] = {{ACT_AddLabel,2,{3,1}}};
TableData TblLabeledStatementNoShortIf_data[3] ={{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=24}},{DT_Subtable, &TblStatementNoShortIf}};
RuleTable TblLabeledStatementNoShortIf ={ET_Concatenate, RP_NA, 3, TblLabeledStatementNoShortIf_data, 1, TblLabeledStatementNoShortIf_action};
TableData TblExpressionStatement_data[2] ={{DT_Subtable, &TblStatementExpression},{DT_Token, {.mTokenId=45}}};
RuleTable TblExpressionStatement ={ET_Concatenate, RP_NA, 2, TblExpressionStatement_data, 0, NULL};
TableData TblStatementExpression_data[7] ={{DT_Subtable, &TblAssignment},{DT_Subtable, &TblPreIncrementExpression},{DT_Subtable, &TblPreDecrementExpression},{DT_Subtable, &TblPostIncrementExpression},{DT_Subtable, &TblPostDecrementExpression},{DT_Subtable, &TblMethodInvocation},{DT_Subtable, &TblClassInstanceCreationExpression}};
RuleTable TblStatementExpression ={ET_Oneof, RP_NA, 7, TblStatementExpression_data, 0, NULL};
TableData TblAssertStatement_sub1_data[3] ={{DT_Token, {.mTokenId=74}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=45}}};
RuleTable TblAssertStatement_sub1 ={ET_Concatenate, RP_NA, 3, TblAssertStatement_sub1_data, 0, NULL};
TableData TblAssertStatement_sub2_data[5] ={{DT_Token, {.mTokenId=74}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=24}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=45}}};
RuleTable TblAssertStatement_sub2 ={ET_Concatenate, RP_NA, 5, TblAssertStatement_sub2_data, 0, NULL};
TableData TblAssertStatement_data[2] ={{DT_Subtable, &TblAssertStatement_sub1},{DT_Subtable, &TblAssertStatement_sub2}};
RuleTable TblAssertStatement ={ET_Oneof, RP_NA, 2, TblAssertStatement_data, 0, NULL};
Action TblSwitchStatement_action[1] = {{ACT_BuildSwitch,2,{3,5}}};
TableData TblSwitchStatement_data[5] ={{DT_Token, {.mTokenId=75}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblSwitchBlock}};
RuleTable TblSwitchStatement ={ET_Concatenate, RP_NA, 5, TblSwitchStatement_data, 1, TblSwitchStatement_action};
Action TblSwitchBlock_action[1] = {{ACT_BuildAllCases,1,{2}}};
TableData TblSwitchBlock_sub3_data[1] ={{DT_Subtable, &TblSwitchBlockStatementGroup}};
RuleTable TblSwitchBlock_sub3 ={ET_Zeroormore, RP_NA, 1, TblSwitchBlock_sub3_data, 0, NULL};
TableData TblSwitchBlock_sub4_data[1] ={{DT_Subtable, &TblSwitchLabel}};
RuleTable TblSwitchBlock_sub4 ={ET_Zeroormore, RP_NA, 1, TblSwitchBlock_sub4_data, 0, NULL};
TableData TblSwitchBlock_sub2_data[2] ={{DT_Subtable, &TblSwitchBlock_sub3},{DT_Subtable, &TblSwitchBlock_sub4}};
RuleTable TblSwitchBlock_sub2 ={ET_Concatenate, RP_NA, 2, TblSwitchBlock_sub2_data, 0, NULL};
TableData TblSwitchBlock_sub1_data[1] ={{DT_Subtable, &TblSwitchBlock_sub2}};
RuleTable TblSwitchBlock_sub1 ={ET_Zeroormore, RP_NA, 1, TblSwitchBlock_sub1_data, 0, NULL};
TableData TblSwitchBlock_data[3] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblSwitchBlock_sub1},{DT_Token, {.mTokenId=48}}};
RuleTable TblSwitchBlock ={ET_Concatenate, RP_NA, 3, TblSwitchBlock_data, 1, TblSwitchBlock_action};
Action TblSwitchBlockStatementGroup_action[1] = {{ACT_BuildOneCase,2,{1,2}}};
TableData TblSwitchBlockStatementGroup_data[2] ={{DT_Subtable, &TblSwitchLabels},{DT_Subtable, &TblBlockStatements}};
RuleTable TblSwitchBlockStatementGroup ={ET_Concatenate, RP_NA, 2, TblSwitchBlockStatementGroup_data, 1, TblSwitchBlockStatementGroup_action};
TableData TblSwitchLabels_sub1_data[1] ={{DT_Subtable, &TblSwitchLabel}};
RuleTable TblSwitchLabels_sub1 ={ET_Zeroormore, RP_NA, 1, TblSwitchLabels_sub1_data, 0, NULL};
TableData TblSwitchLabels_data[2] ={{DT_Subtable, &TblSwitchLabel},{DT_Subtable, &TblSwitchLabels_sub1}};
RuleTable TblSwitchLabels ={ET_Concatenate, RP_NA, 2, TblSwitchLabels_data, 0, NULL};
Action TblSwitchLabel_sub1_action[1] = {{ACT_BuildSwitchLabel,1,{2}}};
TableData TblSwitchLabel_sub1_data[3] ={{DT_Token, {.mTokenId=91}},{DT_Subtable, &TblConstantExpression},{DT_Token, {.mTokenId=24}}};
RuleTable TblSwitchLabel_sub1 ={ET_Concatenate, RP_NA, 3, TblSwitchLabel_sub1_data, 1, TblSwitchLabel_sub1_action};
Action TblSwitchLabel_sub2_action[1] = {{ACT_BuildSwitchLabel,1,{2}}};
TableData TblSwitchLabel_sub2_data[3] ={{DT_Token, {.mTokenId=91}},{DT_Subtable, &TblEnumConstantName},{DT_Token, {.mTokenId=24}}};
RuleTable TblSwitchLabel_sub2 ={ET_Concatenate, RP_NA, 3, TblSwitchLabel_sub2_data, 1, TblSwitchLabel_sub2_action};
Action TblSwitchLabel_sub3_action[1] = {{ACT_BuildDefaultSwitchLabel,0,{}}};
TableData TblSwitchLabel_sub3_data[2] ={{DT_Token, {.mTokenId=66}},{DT_Token, {.mTokenId=24}}};
RuleTable TblSwitchLabel_sub3 ={ET_Concatenate, RP_NA, 2, TblSwitchLabel_sub3_data, 1, TblSwitchLabel_sub3_action};
TableData TblSwitchLabel_data[3] ={{DT_Subtable, &TblSwitchLabel_sub1},{DT_Subtable, &TblSwitchLabel_sub2},{DT_Subtable, &TblSwitchLabel_sub3}};
RuleTable TblSwitchLabel ={ET_Oneof, RP_NA, 3, TblSwitchLabel_data, 0, NULL};
TableData TblEnumConstantName_data[1] ={{DT_Subtable, &TblIdentifier}};
RuleTable TblEnumConstantName ={ET_Data, RP_NA, 1, TblEnumConstantName_data, 0, NULL};
Action TblWhileStatement_action[1] = {{ACT_BuildWhileLoop,2,{3,5}}};
TableData TblWhileStatement_data[5] ={{DT_Token, {.mTokenId=82}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatement}};
RuleTable TblWhileStatement ={ET_Concatenate, RP_NA, 5, TblWhileStatement_data, 1, TblWhileStatement_action};
Action TblWhileStatementNoShortIf_action[1] = {{ACT_BuildWhileLoop,2,{3,5}}};
TableData TblWhileStatementNoShortIf_data[5] ={{DT_Token, {.mTokenId=82}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatementNoShortIf}};
RuleTable TblWhileStatementNoShortIf ={ET_Concatenate, RP_NA, 5, TblWhileStatementNoShortIf_data, 1, TblWhileStatementNoShortIf_action};
Action TblDoStatement_action[1] = {{ACT_BuildDoLoop,2,{5,2}}};
TableData TblDoStatement_data[7] ={{DT_Token, {.mTokenId=103}},{DT_Subtable, &TblStatement},{DT_Token, {.mTokenId=82}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Token, {.mTokenId=45}}};
RuleTable TblDoStatement ={ET_Concatenate, RP_NA, 7, TblDoStatement_data, 1, TblDoStatement_action};
TableData TblForStatement_data[2] ={{DT_Subtable, &TblBasicForStatement},{DT_Subtable, &TblEnhancedForStatement}};
RuleTable TblForStatement ={ET_Oneof, RP_NA, 2, TblForStatement_data, 0, NULL};
TableData TblForStatementNoShortIf_data[2] ={{DT_Subtable, &TblBasicForStatementNoShortIf},{DT_Subtable, &TblEnhancedForStatementNoShortIf}};
RuleTable TblForStatementNoShortIf ={ET_Oneof, RP_NA, 2, TblForStatementNoShortIf_data, 0, NULL};
Action TblBasicForStatement_action[1] = {{ACT_BuildForLoop,4,{3,5,7,9}}};
TableData TblBasicForStatement_sub1_data[1] ={{DT_Subtable, &TblForInit}};
RuleTable TblBasicForStatement_sub1 ={ET_Zeroorone, RP_NA, 1, TblBasicForStatement_sub1_data, 0, NULL};
TableData TblBasicForStatement_sub2_data[1] ={{DT_Subtable, &TblExpression}};
RuleTable TblBasicForStatement_sub2 ={ET_Zeroorone, RP_NA, 1, TblBasicForStatement_sub2_data, 0, NULL};
TableData TblBasicForStatement_sub3_data[1] ={{DT_Subtable, &TblForUpdate}};
RuleTable TblBasicForStatement_sub3 ={ET_Zeroorone, RP_NA, 1, TblBasicForStatement_sub3_data, 0, NULL};
TableData TblBasicForStatement_data[9] ={{DT_Token, {.mTokenId=99}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblBasicForStatement_sub1},{DT_Token, {.mTokenId=45}},{DT_Subtable, &TblBasicForStatement_sub2},{DT_Token, {.mTokenId=45}},{DT_Subtable, &TblBasicForStatement_sub3},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatement}};
RuleTable TblBasicForStatement ={ET_Concatenate, RP_NA, 9, TblBasicForStatement_data, 1, TblBasicForStatement_action};
Action TblBasicForStatementNoShortIf_action[1] = {{ACT_BuildForLoop,4,{3,5,7,9}}};
TableData TblBasicForStatementNoShortIf_sub1_data[1] ={{DT_Subtable, &TblForInit}};
RuleTable TblBasicForStatementNoShortIf_sub1 ={ET_Zeroorone, RP_NA, 1, TblBasicForStatementNoShortIf_sub1_data, 0, NULL};
TableData TblBasicForStatementNoShortIf_sub2_data[1] ={{DT_Subtable, &TblExpression}};
RuleTable TblBasicForStatementNoShortIf_sub2 ={ET_Zeroorone, RP_NA, 1, TblBasicForStatementNoShortIf_sub2_data, 0, NULL};
TableData TblBasicForStatementNoShortIf_sub3_data[1] ={{DT_Subtable, &TblForUpdate}};
RuleTable TblBasicForStatementNoShortIf_sub3 ={ET_Zeroorone, RP_NA, 1, TblBasicForStatementNoShortIf_sub3_data, 0, NULL};
TableData TblBasicForStatementNoShortIf_data[9] ={{DT_Token, {.mTokenId=99}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblBasicForStatementNoShortIf_sub1},{DT_Token, {.mTokenId=45}},{DT_Subtable, &TblBasicForStatementNoShortIf_sub2},{DT_Token, {.mTokenId=45}},{DT_Subtable, &TblBasicForStatementNoShortIf_sub3},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatementNoShortIf}};
RuleTable TblBasicForStatementNoShortIf ={ET_Concatenate, RP_NA, 9, TblBasicForStatementNoShortIf_data, 1, TblBasicForStatementNoShortIf_action};
TableData TblForInit_data[2] ={{DT_Subtable, &TblStatementExpressionList},{DT_Subtable, &TblLocalVariableDeclaration}};
RuleTable TblForInit ={ET_Oneof, RP_NA, 2, TblForInit_data, 0, NULL};
TableData TblForUpdate_data[1] ={{DT_Subtable, &TblStatementExpressionList}};
RuleTable TblForUpdate ={ET_Data, RP_NA, 1, TblForUpdate_data, 0, NULL};
TableData TblStatementExpressionList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblStatementExpression}};
RuleTable TblStatementExpressionList_sub2 ={ET_Concatenate, RP_NA, 2, TblStatementExpressionList_sub2_data, 0, NULL};
TableData TblStatementExpressionList_sub1_data[1] ={{DT_Subtable, &TblStatementExpressionList_sub2}};
RuleTable TblStatementExpressionList_sub1 ={ET_Zeroormore, RP_NA, 1, TblStatementExpressionList_sub1_data, 0, NULL};
TableData TblStatementExpressionList_data[2] ={{DT_Subtable, &TblStatementExpression},{DT_Subtable, &TblStatementExpressionList_sub1}};
RuleTable TblStatementExpressionList ={ET_Concatenate, RP_NA, 2, TblStatementExpressionList_data, 0, NULL};
TableData TblEnhancedForStatement_sub1_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblEnhancedForStatement_sub1 ={ET_Zeroormore, RP_NA, 1, TblEnhancedForStatement_sub1_data, 0, NULL};
TableData TblEnhancedForStatement_data[9] ={{DT_Token, {.mTokenId=99}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblEnhancedForStatement_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblVariableDeclaratorId},{DT_Token, {.mTokenId=24}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatement}};
RuleTable TblEnhancedForStatement ={ET_Concatenate, RP_NA, 9, TblEnhancedForStatement_data, 0, NULL};
TableData TblEnhancedForStatementNoShortIf_sub1_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblEnhancedForStatementNoShortIf_sub1 ={ET_Zeroormore, RP_NA, 1, TblEnhancedForStatementNoShortIf_sub1_data, 0, NULL};
TableData TblEnhancedForStatementNoShortIf_data[9] ={{DT_Token, {.mTokenId=99}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblEnhancedForStatementNoShortIf_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblVariableDeclaratorId},{DT_Token, {.mTokenId=24}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblStatementNoShortIf}};
RuleTable TblEnhancedForStatementNoShortIf ={ET_Concatenate, RP_NA, 9, TblEnhancedForStatementNoShortIf_data, 0, NULL};
Action TblBreakStatement_action[1] = {{ACT_BuildBreak,1,{2}}};
TableData TblBreakStatement_sub1_data[1] ={{DT_Subtable, &TblIdentifier}};
RuleTable TblBreakStatement_sub1 ={ET_Zeroorone, RP_NA, 1, TblBreakStatement_sub1_data, 0, NULL};
TableData TblBreakStatement_data[3] ={{DT_Token, {.mTokenId=84}},{DT_Subtable, &TblBreakStatement_sub1},{DT_Token, {.mTokenId=45}}};
RuleTable TblBreakStatement ={ET_Concatenate, RP_NA, 3, TblBreakStatement_data, 1, TblBreakStatement_action};
TableData TblContinueStatement_sub1_data[1] ={{DT_Subtable, &TblIdentifier}};
RuleTable TblContinueStatement_sub1 ={ET_Zeroorone, RP_NA, 1, TblContinueStatement_sub1_data, 0, NULL};
TableData TblContinueStatement_data[3] ={{DT_Token, {.mTokenId=62}},{DT_Subtable, &TblContinueStatement_sub1},{DT_Token, {.mTokenId=45}}};
RuleTable TblContinueStatement ={ET_Concatenate, RP_NA, 3, TblContinueStatement_data, 0, NULL};
Action TblReturnStatement_action[1] = {{ACT_BuildReturn,1,{2}}};
TableData TblReturnStatement_sub1_data[1] ={{DT_Subtable, &TblExpression}};
RuleTable TblReturnStatement_sub1 ={ET_Zeroorone, RP_NA, 1, TblReturnStatement_sub1_data, 0, NULL};
TableData TblReturnStatement_data[3] ={{DT_Token, {.mTokenId=76}},{DT_Subtable, &TblReturnStatement_sub1},{DT_Token, {.mTokenId=45}}};
RuleTable TblReturnStatement ={ET_Concatenate, RP_NA, 3, TblReturnStatement_data, 1, TblReturnStatement_action};
TableData TblThrowStatement_data[3] ={{DT_Token, {.mTokenId=79}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=45}}};
RuleTable TblThrowStatement ={ET_Concatenate, RP_NA, 3, TblThrowStatement_data, 0, NULL};
TableData TblSynchronizedStatement_data[5] ={{DT_Token, {.mTokenId=53}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExpression},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblBlock}};
RuleTable TblSynchronizedStatement ={ET_Concatenate, RP_NA, 5, TblSynchronizedStatement_data, 0, NULL};
TableData TblTryStatement_sub1_data[3] ={{DT_Token, {.mTokenId=98}},{DT_Subtable, &TblBlock},{DT_Subtable, &TblCatches}};
RuleTable TblTryStatement_sub1 ={ET_Concatenate, RP_NA, 3, TblTryStatement_sub1_data, 0, NULL};
TableData TblTryStatement_sub3_data[1] ={{DT_Subtable, &TblCatches}};
RuleTable TblTryStatement_sub3 ={ET_Zeroorone, RP_NA, 1, TblTryStatement_sub3_data, 0, NULL};
TableData TblTryStatement_sub2_data[4] ={{DT_Token, {.mTokenId=98}},{DT_Subtable, &TblBlock},{DT_Subtable, &TblTryStatement_sub3},{DT_Subtable, &TblFinally}};
RuleTable TblTryStatement_sub2 ={ET_Concatenate, RP_NA, 4, TblTryStatement_sub2_data, 0, NULL};
TableData TblTryStatement_data[3] ={{DT_Subtable, &TblTryStatement_sub1},{DT_Subtable, &TblTryStatement_sub2},{DT_Subtable, &TblTryWithResourcesStatement}};
RuleTable TblTryStatement ={ET_Oneof, RP_NA, 3, TblTryStatement_data, 0, NULL};
TableData TblCatches_sub1_data[1] ={{DT_Subtable, &TblCatchClause}};
RuleTable TblCatches_sub1 ={ET_Zeroormore, RP_NA, 1, TblCatches_sub1_data, 0, NULL};
TableData TblCatches_data[2] ={{DT_Subtable, &TblCatchClause},{DT_Subtable, &TblCatches_sub1}};
RuleTable TblCatches ={ET_Concatenate, RP_NA, 2, TblCatches_data, 0, NULL};
TableData TblCatchClause_data[5] ={{DT_Token, {.mTokenId=83}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblCatchFormalParameter},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblBlock}};
RuleTable TblCatchClause ={ET_Concatenate, RP_NA, 5, TblCatchClause_data, 0, NULL};
TableData TblCatchFormalParameter_sub1_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblCatchFormalParameter_sub1 ={ET_Zeroormore, RP_NA, 1, TblCatchFormalParameter_sub1_data, 0, NULL};
TableData TblCatchFormalParameter_data[3] ={{DT_Subtable, &TblCatchFormalParameter_sub1},{DT_Subtable, &TblCatchType},{DT_Subtable, &TblVariableDeclaratorId}};
RuleTable TblCatchFormalParameter ={ET_Concatenate, RP_NA, 3, TblCatchFormalParameter_data, 0, NULL};
TableData TblCatchType_sub2_data[2] ={{DT_Token, {.mTokenId=29}},{DT_Subtable, &TblClassType}};
RuleTable TblCatchType_sub2 ={ET_Concatenate, RP_NA, 2, TblCatchType_sub2_data, 0, NULL};
TableData TblCatchType_sub1_data[1] ={{DT_Subtable, &TblCatchType_sub2}};
RuleTable TblCatchType_sub1 ={ET_Zeroormore, RP_NA, 1, TblCatchType_sub1_data, 0, NULL};
TableData TblCatchType_data[2] ={{DT_Subtable, &TblUnannClassType},{DT_Subtable, &TblCatchType_sub1}};
RuleTable TblCatchType ={ET_Concatenate, RP_NA, 2, TblCatchType_data, 0, NULL};
TableData TblFinally_data[2] ={{DT_Token, {.mTokenId=65}},{DT_Subtable, &TblBlock}};
RuleTable TblFinally ={ET_Concatenate, RP_NA, 2, TblFinally_data, 0, NULL};
TableData TblTryWithResourcesStatement_sub1_data[1] ={{DT_Subtable, &TblCatches}};
RuleTable TblTryWithResourcesStatement_sub1 ={ET_Zeroorone, RP_NA, 1, TblTryWithResourcesStatement_sub1_data, 0, NULL};
TableData TblTryWithResourcesStatement_sub2_data[1] ={{DT_Subtable, &TblFinally}};
RuleTable TblTryWithResourcesStatement_sub2 ={ET_Zeroorone, RP_NA, 1, TblTryWithResourcesStatement_sub2_data, 0, NULL};
TableData TblTryWithResourcesStatement_data[5] ={{DT_Token, {.mTokenId=98}},{DT_Subtable, &TblResourceSpecification},{DT_Subtable, &TblBlock},{DT_Subtable, &TblTryWithResourcesStatement_sub1},{DT_Subtable, &TblTryWithResourcesStatement_sub2}};
RuleTable TblTryWithResourcesStatement ={ET_Concatenate, RP_NA, 5, TblTryWithResourcesStatement_data, 0, NULL};
TableData TblResourceSpecification_sub1_data[1] ={{DT_Token, {.mTokenId=45}}};
RuleTable TblResourceSpecification_sub1 ={ET_Zeroorone, RP_NA, 1, TblResourceSpecification_sub1_data, 0, NULL};
TableData TblResourceSpecification_data[4] ={{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblResourceList},{DT_Subtable, &TblResourceSpecification_sub1},{DT_Token, {.mTokenId=50}}};
RuleTable TblResourceSpecification ={ET_Concatenate, RP_NA, 4, TblResourceSpecification_data, 0, NULL};
TableData TblResourceList_sub2_data[2] ={{DT_Token, {.mTokenId=45}},{DT_Subtable, &TblResource}};
RuleTable TblResourceList_sub2 ={ET_Concatenate, RP_NA, 2, TblResourceList_sub2_data, 0, NULL};
TableData TblResourceList_sub1_data[1] ={{DT_Subtable, &TblResourceList_sub2}};
RuleTable TblResourceList_sub1 ={ET_Zeroormore, RP_NA, 1, TblResourceList_sub1_data, 0, NULL};
TableData TblResourceList_data[2] ={{DT_Subtable, &TblResource},{DT_Subtable, &TblResourceList_sub1}};
RuleTable TblResourceList ={ET_Concatenate, RP_NA, 2, TblResourceList_data, 0, NULL};
TableData TblResource_sub2_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblResource_sub2 ={ET_Zeroormore, RP_NA, 1, TblResource_sub2_data, 0, NULL};
TableData TblResource_sub1_data[5] ={{DT_Subtable, &TblResource_sub2},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=25}},{DT_Subtable, &TblExpression}};
RuleTable TblResource_sub1 ={ET_Concatenate, RP_NA, 5, TblResource_sub1_data, 0, NULL};
TableData TblResource_data[2] ={{DT_Subtable, &TblResource_sub1},{DT_Subtable, &TblVariableAccess}};
RuleTable TblResource ={ET_Oneof, RP_NA, 2, TblResource_data, 0, NULL};
TableData TblVariableAccess_data[2] ={{DT_Subtable, &TblExpressionName},{DT_Subtable, &TblFieldAccess}};
RuleTable TblVariableAccess ={ET_Oneof, RP_NA, 2, TblVariableAccess_data, 0, NULL};
