#include "common_header_autogen.h"
TableData TblClassDeclaration_data[2] ={{DT_Subtable, &TblNormalClassDeclaration},{DT_Subtable, &TblEnumDeclaration}};
RuleTable TblClassDeclaration ={ET_Oneof, RP_Single, 2, TblClassDeclaration_data, 0, NULL};
Action TblNormalClassDeclaration_action[5] = {{ACT_BuildClass,1,{3}},{ACT_AddModifier,1,{1}},{ACT_AddClassBody,1,{7}},{ACT_AddSuperClass,1,{5}},{ACT_AddSuperInterface,1,{6}}};
TableData TblNormalClassDeclaration_sub1_data[1] ={{DT_Subtable, &TblClassModifier}};
RuleTable TblNormalClassDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblNormalClassDeclaration_sub1_data, 0, NULL};
TableData TblNormalClassDeclaration_sub2_data[1] ={{DT_Subtable, &TblTypeParameters}};
RuleTable TblNormalClassDeclaration_sub2 ={ET_Zeroorone, RP_NA, 1, TblNormalClassDeclaration_sub2_data, 0, NULL};
TableData TblNormalClassDeclaration_sub3_data[1] ={{DT_Subtable, &TblSuperclass}};
RuleTable TblNormalClassDeclaration_sub3 ={ET_Zeroorone, RP_NA, 1, TblNormalClassDeclaration_sub3_data, 0, NULL};
TableData TblNormalClassDeclaration_sub4_data[1] ={{DT_Subtable, &TblSuperinterfaces}};
RuleTable TblNormalClassDeclaration_sub4 ={ET_Zeroorone, RP_NA, 1, TblNormalClassDeclaration_sub4_data, 0, NULL};
TableData TblNormalClassDeclaration_data[7] ={{DT_Subtable, &TblNormalClassDeclaration_sub1},{DT_Token, {.mTokenId=87}},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblNormalClassDeclaration_sub2},{DT_Subtable, &TblNormalClassDeclaration_sub3},{DT_Subtable, &TblNormalClassDeclaration_sub4},{DT_Subtable, &TblClassBody}};
RuleTable TblNormalClassDeclaration ={ET_Concatenate, RP_NA, 7, TblNormalClassDeclaration_data, 5, TblNormalClassDeclaration_action};
TableData TblClassAttr_data[7] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=56}},{DT_Token, {.mTokenId=63}},{DT_Token, {.mTokenId=61}},{DT_Token, {.mTokenId=69}},{DT_Token, {.mTokenId=78}},{DT_Token, {.mTokenId=59}}};
RuleTable TblClassAttr ={ET_Oneof, RP_Single, 7, TblClassAttr_data, 0, NULL};
TableData TblClassModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblClassAttr}};
RuleTable TblClassModifier ={ET_Oneof, RP_Single, 2, TblClassModifier_data, 0, NULL};
TableData TblTypeParameters_data[3] ={{DT_Token, {.mTokenId=31}},{DT_Subtable, &TblTypeParameterList},{DT_Token, {.mTokenId=32}}};
RuleTable TblTypeParameters ={ET_Concatenate, RP_NA, 3, TblTypeParameters_data, 0, NULL};
TableData TblTypeParameterList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblTypeParameter}};
RuleTable TblTypeParameterList_sub2 ={ET_Concatenate, RP_NA, 2, TblTypeParameterList_sub2_data, 0, NULL};
TableData TblTypeParameterList_sub1_data[1] ={{DT_Subtable, &TblTypeParameterList_sub2}};
RuleTable TblTypeParameterList_sub1 ={ET_Zeroormore, RP_NA, 1, TblTypeParameterList_sub1_data, 0, NULL};
TableData TblTypeParameterList_data[2] ={{DT_Subtable, &TblTypeParameter},{DT_Subtable, &TblTypeParameterList_sub1}};
RuleTable TblTypeParameterList ={ET_Concatenate, RP_NA, 2, TblTypeParameterList_data, 0, NULL};
TableData TblTypeParameter_sub1_data[1] ={{DT_Subtable, &TblTypeParameterModifier}};
RuleTable TblTypeParameter_sub1 ={ET_Zeroormore, RP_NA, 1, TblTypeParameter_sub1_data, 0, NULL};
TableData TblTypeParameter_sub2_data[1] ={{DT_Subtable, &TblTypeBound}};
RuleTable TblTypeParameter_sub2 ={ET_Zeroorone, RP_NA, 1, TblTypeParameter_sub2_data, 0, NULL};
TableData TblTypeParameter_data[3] ={{DT_Subtable, &TblTypeParameter_sub1},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblTypeParameter_sub2}};
RuleTable TblTypeParameter ={ET_Concatenate, RP_NA, 3, TblTypeParameter_data, 0, NULL};
TableData TblTypeParameterModifier_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblTypeParameterModifier ={ET_Data, RP_NA, 1, TblTypeParameterModifier_data, 0, NULL};
TableData TblTypeBound_sub1_data[2] ={{DT_Token, {.mTokenId=64}},{DT_Subtable, &TblTypeVariable}};
RuleTable TblTypeBound_sub1 ={ET_Concatenate, RP_NA, 2, TblTypeBound_sub1_data, 0, NULL};
TableData TblTypeBound_sub3_data[1] ={{DT_Subtable, &TblAdditionalBound}};
RuleTable TblTypeBound_sub3 ={ET_Zeroormore, RP_NA, 1, TblTypeBound_sub3_data, 0, NULL};
TableData TblTypeBound_sub2_data[3] ={{DT_Token, {.mTokenId=64}},{DT_Subtable, &TblClassOrInterfaceType},{DT_Subtable, &TblTypeBound_sub3}};
RuleTable TblTypeBound_sub2 ={ET_Concatenate, RP_NA, 3, TblTypeBound_sub2_data, 0, NULL};
TableData TblTypeBound_data[2] ={{DT_Subtable, &TblTypeBound_sub1},{DT_Subtable, &TblTypeBound_sub2}};
RuleTable TblTypeBound ={ET_Oneof, RP_NA, 2, TblTypeBound_data, 0, NULL};
TableData TblAdditionalBound_data[2] ={{DT_Token, {.mTokenId=30}},{DT_Subtable, &TblInterfaceType}};
RuleTable TblAdditionalBound ={ET_Concatenate, RP_NA, 2, TblAdditionalBound_data, 0, NULL};
TableData TblSuperclass_data[2] ={{DT_Token, {.mTokenId=64}},{DT_Subtable, &TblClassType}};
RuleTable TblSuperclass ={ET_Concatenate, RP_NA, 2, TblSuperclass_data, 0, NULL};
TableData TblSuperinterfaces_data[2] ={{DT_Token, {.mTokenId=54}},{DT_Subtable, &TblInterfaceTypeList}};
RuleTable TblSuperinterfaces ={ET_Concatenate, RP_NA, 2, TblSuperinterfaces_data, 0, NULL};
TableData TblInterfaceTypeList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblInterfaceType}};
RuleTable TblInterfaceTypeList_sub2 ={ET_Concatenate, RP_NA, 2, TblInterfaceTypeList_sub2_data, 0, NULL};
TableData TblInterfaceTypeList_sub1_data[1] ={{DT_Subtable, &TblInterfaceTypeList_sub2}};
RuleTable TblInterfaceTypeList_sub1 ={ET_Zeroormore, RP_NA, 1, TblInterfaceTypeList_sub1_data, 0, NULL};
TableData TblInterfaceTypeList_data[2] ={{DT_Subtable, &TblInterfaceType},{DT_Subtable, &TblInterfaceTypeList_sub1}};
RuleTable TblInterfaceTypeList ={ET_Concatenate, RP_NA, 2, TblInterfaceTypeList_data, 0, NULL};
Action TblClassBody_action[1] = {{ACT_BuildBlock,1,{2}}};
TableData TblClassBody_sub1_data[1] ={{DT_Subtable, &TblClassBodyDeclaration}};
RuleTable TblClassBody_sub1 ={ET_Zeroormore, RP_NA, 1, TblClassBody_sub1_data, 0, NULL};
TableData TblClassBody_data[3] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblClassBody_sub1},{DT_Token, {.mTokenId=48}}};
RuleTable TblClassBody ={ET_Concatenate, RP_NA, 3, TblClassBody_data, 1, TblClassBody_action};
TableData TblClassBodyDeclaration_data[4] ={{DT_Subtable, &TblClassMemberDeclaration},{DT_Subtable, &TblInstanceInitializer},{DT_Subtable, &TblStaticInitializer},{DT_Subtable, &TblConstructorDeclaration}};
RuleTable TblClassBodyDeclaration ={ET_Oneof, RP_Single, 4, TblClassBodyDeclaration_data, 0, NULL};
Action TblInstanceInitializer_action[1] = {{ACT_BuildInstInit,1,{1}}};
TableData TblInstanceInitializer_data[1] ={{DT_Subtable, &TblBlock}};
RuleTable TblInstanceInitializer ={ET_Data, RP_NA, 1, TblInstanceInitializer_data, 1, TblInstanceInitializer_action};
Action TblStaticInitializer_action[2] = {{ACT_BuildInstInit,1,{2}},{ACT_AddModifierTo,2,{2,1}}};
TableData TblStaticInitializer_data[2] ={{DT_Token, {.mTokenId=69}},{DT_Subtable, &TblBlock}};
RuleTable TblStaticInitializer ={ET_Concatenate, RP_NA, 2, TblStaticInitializer_data, 2, TblStaticInitializer_action};
TableData TblClassMemberDeclaration_data[5] ={{DT_Subtable, &TblFieldDeclaration},{DT_Subtable, &TblMethodDeclaration},{DT_Subtable, &TblClassDeclaration},{DT_Subtable, &TblInterfaceDeclaration},{DT_Token, {.mTokenId=45}}};
RuleTable TblClassMemberDeclaration ={ET_Oneof, RP_Single, 5, TblClassMemberDeclaration_data, 0, NULL};
Action TblFieldDeclaration_action[2] = {{ACT_BuildDecl,2,{2,3}},{ACT_AddModifier,1,{1}}};
TableData TblFieldDeclaration_sub1_data[1] ={{DT_Subtable, &TblFieldModifier}};
RuleTable TblFieldDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblFieldDeclaration_sub1_data, 0, NULL};
TableData TblFieldDeclaration_data[4] ={{DT_Subtable, &TblFieldDeclaration_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblVariableDeclaratorList},{DT_Token, {.mTokenId=45}}};
RuleTable TblFieldDeclaration ={ET_Concatenate, RP_NA, 4, TblFieldDeclaration_data, 2, TblFieldDeclaration_action};
Action TblMethodDeclaration_action[2] = {{ACT_AddModifierTo,2,{2,1}},{ACT_AddFunctionBodyTo,2,{2,3}}};
TableData TblMethodDeclaration_sub1_data[1] ={{DT_Subtable, &TblMethodModifier}};
RuleTable TblMethodDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblMethodDeclaration_sub1_data, 0, NULL};
TableData TblMethodDeclaration_data[3] ={{DT_Subtable, &TblMethodDeclaration_sub1},{DT_Subtable, &TblMethodHeader},{DT_Subtable, &TblMethodBody}};
RuleTable TblMethodDeclaration ={ET_Concatenate, RP_NA, 3, TblMethodDeclaration_data, 2, TblMethodDeclaration_action};
TableData TblMethodBody_data[2] ={{DT_Subtable, &TblBlock},{DT_Token, {.mTokenId=45}}};
RuleTable TblMethodBody ={ET_Oneof, RP_Single, 2, TblMethodBody_data, 0, NULL};
Action TblMethodHeader_sub1_action[2] = {{ACT_AddTypeTo,2,{2,1}},{ACT_AddThrowsTo,2,{2,3}}};
TableData TblMethodHeader_sub2_data[1] ={{DT_Subtable, &TblThrows}};
RuleTable TblMethodHeader_sub2 ={ET_Zeroorone, RP_NA, 1, TblMethodHeader_sub2_data, 0, NULL};
TableData TblMethodHeader_sub1_data[3] ={{DT_Subtable, &TblResult},{DT_Subtable, &TblMethodDeclarator},{DT_Subtable, &TblMethodHeader_sub2}};
RuleTable TblMethodHeader_sub1 ={ET_Concatenate, RP_NA, 3, TblMethodHeader_sub1_data, 2, TblMethodHeader_sub1_action};
Action TblMethodHeader_sub3_action[1] = {{ACT_AddThrowsTo,2,{4,5}}};
TableData TblMethodHeader_sub4_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblMethodHeader_sub4 ={ET_Zeroormore, RP_NA, 1, TblMethodHeader_sub4_data, 0, NULL};
TableData TblMethodHeader_sub5_data[1] ={{DT_Subtable, &TblThrows}};
RuleTable TblMethodHeader_sub5 ={ET_Zeroorone, RP_NA, 1, TblMethodHeader_sub5_data, 0, NULL};
TableData TblMethodHeader_sub3_data[5] ={{DT_Subtable, &TblTypeParameters},{DT_Subtable, &TblMethodHeader_sub4},{DT_Subtable, &TblResult},{DT_Subtable, &TblMethodDeclarator},{DT_Subtable, &TblMethodHeader_sub5}};
RuleTable TblMethodHeader_sub3 ={ET_Concatenate, RP_NA, 5, TblMethodHeader_sub3_data, 1, TblMethodHeader_sub3_action};
TableData TblMethodHeader_data[2] ={{DT_Subtable, &TblMethodHeader_sub1},{DT_Subtable, &TblMethodHeader_sub3}};
RuleTable TblMethodHeader ={ET_Oneof, RP_Single, 2, TblMethodHeader_data, 0, NULL};
TableData TblResult_data[2] ={{DT_Subtable, &TblUnannType},{DT_Token, {.mTokenId=92}}};
RuleTable TblResult ={ET_Oneof, RP_Single, 2, TblResult_data, 0, NULL};
Action TblMethodDeclarator_action[3] = {{ACT_BuildFunction,1,{1}},{ACT_AddParams,1,{3}},{ACT_AddDims,1,{5}}};
TableData TblMethodDeclarator_sub1_data[1] ={{DT_Subtable, &TblFormalParameterList}};
RuleTable TblMethodDeclarator_sub1 ={ET_Zeroorone, RP_NA, 1, TblMethodDeclarator_sub1_data, 0, NULL};
TableData TblMethodDeclarator_sub2_data[1] ={{DT_Subtable, &TblDims}};
RuleTable TblMethodDeclarator_sub2 ={ET_Zeroorone, RP_NA, 1, TblMethodDeclarator_sub2_data, 0, NULL};
TableData TblMethodDeclarator_data[5] ={{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblMethodDeclarator_sub1},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblMethodDeclarator_sub2}};
RuleTable TblMethodDeclarator ={ET_Concatenate, RP_NA, 5, TblMethodDeclarator_data, 3, TblMethodDeclarator_action};
Action TblThrows_action[1] = {{ACT_BuildThrows,1,{2}}};
TableData TblThrows_data[2] ={{DT_Token, {.mTokenId=72}},{DT_Subtable, &TblExceptionTypeList}};
RuleTable TblThrows ={ET_Concatenate, RP_NA, 2, TblThrows_data, 1, TblThrows_action};
TableData TblExceptionTypeList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblExceptionType}};
RuleTable TblExceptionTypeList_sub2 ={ET_Concatenate, RP_NA, 2, TblExceptionTypeList_sub2_data, 0, NULL};
TableData TblExceptionTypeList_sub1_data[1] ={{DT_Subtable, &TblExceptionTypeList_sub2}};
RuleTable TblExceptionTypeList_sub1 ={ET_Zeroormore, RP_NA, 1, TblExceptionTypeList_sub1_data, 0, NULL};
TableData TblExceptionTypeList_data[2] ={{DT_Subtable, &TblExceptionType},{DT_Subtable, &TblExceptionTypeList_sub1}};
RuleTable TblExceptionTypeList ={ET_Concatenate, RP_NA, 2, TblExceptionTypeList_data, 0, NULL};
TableData TblExceptionType_data[2] ={{DT_Subtable, &TblClassType},{DT_Subtable, &TblTypeVariable}};
RuleTable TblExceptionType ={ET_Oneof, RP_NA, 2, TblExceptionType_data, 0, NULL};
TableData TblMethodAttr_data[9] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=56}},{DT_Token, {.mTokenId=63}},{DT_Token, {.mTokenId=61}},{DT_Token, {.mTokenId=69}},{DT_Token, {.mTokenId=78}},{DT_Token, {.mTokenId=53}},{DT_Token, {.mTokenId=71}},{DT_Token, {.mTokenId=59}}};
RuleTable TblMethodAttr ={ET_Oneof, RP_Single, 9, TblMethodAttr_data, 0, NULL};
TableData TblMethodModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblMethodAttr}};
RuleTable TblMethodModifier ={ET_Oneof, RP_Single, 2, TblMethodModifier_data, 0, NULL};
Action TblFormalParameterListNoReceiver_sub1_action[1] = {{ACT_BuildVarList,2,{1,3}}};
TableData TblFormalParameterListNoReceiver_sub1_data[3] ={{DT_Subtable, &TblFormalParameters},{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblLastFormalParameter}};
RuleTable TblFormalParameterListNoReceiver_sub1 ={ET_Concatenate, RP_NA, 3, TblFormalParameterListNoReceiver_sub1_data, 1, TblFormalParameterListNoReceiver_sub1_action};
TableData TblFormalParameterListNoReceiver_data[2] ={{DT_Subtable, &TblFormalParameterListNoReceiver_sub1},{DT_Subtable, &TblLastFormalParameter}};
RuleTable TblFormalParameterListNoReceiver ={ET_Oneof, RP_NA, 2, TblFormalParameterListNoReceiver_data, 0, NULL};
TableData TblFormalParameterList_data[2] ={{DT_Subtable, &TblReceiverParameter},{DT_Subtable, &TblFormalParameterListNoReceiver}};
RuleTable TblFormalParameterList ={ET_Oneof, RP_Single, 2, TblFormalParameterList_data, 0, NULL};
Action TblFormalParameters_sub1_action[1] = {{ACT_BuildVarList,2,{1,2}}};
TableData TblFormalParameters_sub3_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblFormalParameter}};
RuleTable TblFormalParameters_sub3 ={ET_Concatenate, RP_NA, 2, TblFormalParameters_sub3_data, 0, NULL};
TableData TblFormalParameters_sub2_data[1] ={{DT_Subtable, &TblFormalParameters_sub3}};
RuleTable TblFormalParameters_sub2 ={ET_Zeroormore, RP_NA, 1, TblFormalParameters_sub2_data, 0, NULL};
TableData TblFormalParameters_sub1_data[2] ={{DT_Subtable, &TblFormalParameter},{DT_Subtable, &TblFormalParameters_sub2}};
RuleTable TblFormalParameters_sub1 ={ET_Concatenate, RP_NA, 2, TblFormalParameters_sub1_data, 1, TblFormalParameters_sub1_action};
TableData TblFormalParameters_sub6_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblFormalParameter}};
RuleTable TblFormalParameters_sub6 ={ET_Concatenate, RP_NA, 2, TblFormalParameters_sub6_data, 0, NULL};
TableData TblFormalParameters_sub5_data[1] ={{DT_Subtable, &TblFormalParameters_sub6}};
RuleTable TblFormalParameters_sub5 ={ET_Zeroormore, RP_NA, 1, TblFormalParameters_sub5_data, 0, NULL};
TableData TblFormalParameters_sub4_data[2] ={{DT_Subtable, &TblReceiverParameter},{DT_Subtable, &TblFormalParameters_sub5}};
RuleTable TblFormalParameters_sub4 ={ET_Concatenate, RP_NA, 2, TblFormalParameters_sub4_data, 0, NULL};
TableData TblFormalParameters_data[2] ={{DT_Subtable, &TblFormalParameters_sub1},{DT_Subtable, &TblFormalParameters_sub4}};
RuleTable TblFormalParameters ={ET_Oneof, RP_Single, 2, TblFormalParameters_data, 0, NULL};
Action TblFormalParameter_action[2] = {{ACT_BuildDecl,2,{2,3}},{ACT_AddModifier,1,{1}}};
TableData TblFormalParameter_sub1_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblFormalParameter_sub1 ={ET_Zeroormore, RP_NA, 1, TblFormalParameter_sub1_data, 0, NULL};
TableData TblFormalParameter_data[3] ={{DT_Subtable, &TblFormalParameter_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblVariableDeclaratorId}};
RuleTable TblFormalParameter ={ET_Concatenate, RP_NA, 3, TblFormalParameter_data, 2, TblFormalParameter_action};
TableData TblReceiverParameter_sub1_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblReceiverParameter_sub1 ={ET_Zeroormore, RP_NA, 1, TblReceiverParameter_sub1_data, 0, NULL};
TableData TblReceiverParameter_sub3_data[2] ={{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=43}}};
RuleTable TblReceiverParameter_sub3 ={ET_Concatenate, RP_NA, 2, TblReceiverParameter_sub3_data, 0, NULL};
TableData TblReceiverParameter_sub2_data[1] ={{DT_Subtable, &TblReceiverParameter_sub3}};
RuleTable TblReceiverParameter_sub2 ={ET_Zeroorone, RP_NA, 1, TblReceiverParameter_sub2_data, 0, NULL};
TableData TblReceiverParameter_data[4] ={{DT_Subtable, &TblReceiverParameter_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblReceiverParameter_sub2},{DT_Token, {.mTokenId=88}}};
RuleTable TblReceiverParameter ={ET_Concatenate, RP_NA, 4, TblReceiverParameter_data, 0, NULL};
TableData TblLastFormalParameter_sub2_data[1] ={{DT_Subtable, &TblVariableModifier}};
RuleTable TblLastFormalParameter_sub2 ={ET_Zeroormore, RP_NA, 1, TblLastFormalParameter_sub2_data, 0, NULL};
TableData TblLastFormalParameter_sub3_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblLastFormalParameter_sub3 ={ET_Zeroormore, RP_NA, 1, TblLastFormalParameter_sub3_data, 0, NULL};
TableData TblLastFormalParameter_sub1_data[5] ={{DT_Subtable, &TblLastFormalParameter_sub2},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblLastFormalParameter_sub3},{DT_Token, {.mTokenId=38}},{DT_Subtable, &TblVariableDeclaratorId}};
RuleTable TblLastFormalParameter_sub1 ={ET_Concatenate, RP_NA, 5, TblLastFormalParameter_sub1_data, 0, NULL};
TableData TblLastFormalParameter_data[2] ={{DT_Subtable, &TblLastFormalParameter_sub1},{DT_Subtable, &TblFormalParameter}};
RuleTable TblLastFormalParameter ={ET_Oneof, RP_Single, 2, TblLastFormalParameter_data, 0, NULL};
TableData TblFieldAttr_data[7] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=56}},{DT_Token, {.mTokenId=63}},{DT_Token, {.mTokenId=69}},{DT_Token, {.mTokenId=78}},{DT_Token, {.mTokenId=57}},{DT_Token, {.mTokenId=60}}};
RuleTable TblFieldAttr ={ET_Oneof, RP_Single, 7, TblFieldAttr_data, 0, NULL};
TableData TblFieldModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblFieldAttr}};
RuleTable TblFieldModifier ={ET_Oneof, RP_Single, 2, TblFieldModifier_data, 0, NULL};
Action TblConstructorDeclaration_action[1] = {{ACT_AddFunctionBodyTo,2,{2,4}}};
TableData TblConstructorDeclaration_sub1_data[1] ={{DT_Subtable, &TblConstructorModifier}};
RuleTable TblConstructorDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblConstructorDeclaration_sub1_data, 0, NULL};
TableData TblConstructorDeclaration_sub2_data[1] ={{DT_Subtable, &TblThrows}};
RuleTable TblConstructorDeclaration_sub2 ={ET_Zeroorone, RP_NA, 1, TblConstructorDeclaration_sub2_data, 0, NULL};
TableData TblConstructorDeclaration_data[4] ={{DT_Subtable, &TblConstructorDeclaration_sub1},{DT_Subtable, &TblConstructorDeclarator},{DT_Subtable, &TblConstructorDeclaration_sub2},{DT_Subtable, &TblConstructorBody}};
RuleTable TblConstructorDeclaration ={ET_Concatenate, RP_NA, 4, TblConstructorDeclaration_data, 1, TblConstructorDeclaration_action};
TableData TblConstructorAttr_data[3] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=56}},{DT_Token, {.mTokenId=63}}};
RuleTable TblConstructorAttr ={ET_Oneof, RP_Single, 3, TblConstructorAttr_data, 0, NULL};
TableData TblConstructorModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblConstructorAttr}};
RuleTable TblConstructorModifier ={ET_Oneof, RP_Single, 2, TblConstructorModifier_data, 0, NULL};
Action TblConstructorDeclarator_action[1] = {{ACT_BuildConstructor,1,{2}}};
TableData TblConstructorDeclarator_sub1_data[1] ={{DT_Subtable, &TblTypeParameters}};
RuleTable TblConstructorDeclarator_sub1 ={ET_Zeroorone, RP_NA, 1, TblConstructorDeclarator_sub1_data, 0, NULL};
TableData TblConstructorDeclarator_sub2_data[1] ={{DT_Subtable, &TblFormalParameterList}};
RuleTable TblConstructorDeclarator_sub2 ={ET_Zeroorone, RP_NA, 1, TblConstructorDeclarator_sub2_data, 0, NULL};
TableData TblConstructorDeclarator_data[5] ={{DT_Subtable, &TblConstructorDeclarator_sub1},{DT_Subtable, &TblSimpleTypeName},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblConstructorDeclarator_sub2},{DT_Token, {.mTokenId=50}}};
RuleTable TblConstructorDeclarator ={ET_Concatenate, RP_NA, 5, TblConstructorDeclarator_data, 1, TblConstructorDeclarator_action};
TableData TblSimpleTypeName_data[1] ={{DT_Subtable, &TblIdentifier}};
RuleTable TblSimpleTypeName ={ET_Data, RP_NA, 1, TblSimpleTypeName_data, 0, NULL};
Action TblConstructorBody_action[1] = {{ACT_BuildBlock,1,{3}}};
TableData TblConstructorBody_sub1_data[1] ={{DT_Subtable, &TblExplicitConstructorInvocation}};
RuleTable TblConstructorBody_sub1 ={ET_Zeroorone, RP_NA, 1, TblConstructorBody_sub1_data, 0, NULL};
TableData TblConstructorBody_sub2_data[1] ={{DT_Subtable, &TblBlockStatements}};
RuleTable TblConstructorBody_sub2 ={ET_Zeroorone, RP_NA, 1, TblConstructorBody_sub2_data, 0, NULL};
TableData TblConstructorBody_data[4] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblConstructorBody_sub1},{DT_Subtable, &TblConstructorBody_sub2},{DT_Token, {.mTokenId=48}}};
RuleTable TblConstructorBody ={ET_Concatenate, RP_NA, 4, TblConstructorBody_data, 1, TblConstructorBody_action};
TableData TblExplicitConstructorInvocation_sub2_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblExplicitConstructorInvocation_sub2 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub2_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub3_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblExplicitConstructorInvocation_sub3 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub3_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub1_data[6] ={{DT_Subtable, &TblExplicitConstructorInvocation_sub2},{DT_Token, {.mTokenId=88}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExplicitConstructorInvocation_sub3},{DT_Token, {.mTokenId=50}},{DT_Token, {.mTokenId=45}}};
RuleTable TblExplicitConstructorInvocation_sub1 ={ET_Concatenate, RP_NA, 6, TblExplicitConstructorInvocation_sub1_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub5_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblExplicitConstructorInvocation_sub5 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub5_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub6_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblExplicitConstructorInvocation_sub6 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub6_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub4_data[6] ={{DT_Subtable, &TblExplicitConstructorInvocation_sub5},{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExplicitConstructorInvocation_sub6},{DT_Token, {.mTokenId=50}},{DT_Token, {.mTokenId=45}}};
RuleTable TblExplicitConstructorInvocation_sub4 ={ET_Concatenate, RP_NA, 6, TblExplicitConstructorInvocation_sub4_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub8_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblExplicitConstructorInvocation_sub8 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub8_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub9_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblExplicitConstructorInvocation_sub9 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub9_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub7_data[8] ={{DT_Subtable, &TblExpressionName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblExplicitConstructorInvocation_sub8},{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExplicitConstructorInvocation_sub9},{DT_Token, {.mTokenId=50}},{DT_Token, {.mTokenId=45}}};
RuleTable TblExplicitConstructorInvocation_sub7 ={ET_Concatenate, RP_NA, 8, TblExplicitConstructorInvocation_sub7_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub11_data[1] ={{DT_Subtable, &TblTypeArguments}};
RuleTable TblExplicitConstructorInvocation_sub11 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub11_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub12_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblExplicitConstructorInvocation_sub12 ={ET_Zeroorone, RP_NA, 1, TblExplicitConstructorInvocation_sub12_data, 0, NULL};
TableData TblExplicitConstructorInvocation_sub10_data[8] ={{DT_Subtable, &TblPrimary},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblExplicitConstructorInvocation_sub11},{DT_Token, {.mTokenId=80}},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblExplicitConstructorInvocation_sub12},{DT_Token, {.mTokenId=50}},{DT_Token, {.mTokenId=45}}};
RuleTable TblExplicitConstructorInvocation_sub10 ={ET_Concatenate, RP_NA, 8, TblExplicitConstructorInvocation_sub10_data, 0, NULL};
TableData TblExplicitConstructorInvocation_data[4] ={{DT_Subtable, &TblExplicitConstructorInvocation_sub1},{DT_Subtable, &TblExplicitConstructorInvocation_sub4},{DT_Subtable, &TblExplicitConstructorInvocation_sub7},{DT_Subtable, &TblExplicitConstructorInvocation_sub10}};
RuleTable TblExplicitConstructorInvocation ={ET_Oneof, RP_Single, 4, TblExplicitConstructorInvocation_data, 0, NULL};
Action TblEnumDeclaration_action[5] = {{ACT_BuildClass,1,{3}},{ACT_SetClassIsJavaEnum,0,{}},{ACT_AddModifier,1,{1}},{ACT_AddSuperInterface,1,{4}},{ACT_AddClassBody,1,{5}}};
TableData TblEnumDeclaration_sub1_data[1] ={{DT_Subtable, &TblClassModifier}};
RuleTable TblEnumDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblEnumDeclaration_sub1_data, 0, NULL};
TableData TblEnumDeclaration_sub2_data[1] ={{DT_Subtable, &TblSuperinterfaces}};
RuleTable TblEnumDeclaration_sub2 ={ET_Zeroorone, RP_NA, 1, TblEnumDeclaration_sub2_data, 0, NULL};
TableData TblEnumDeclaration_data[5] ={{DT_Subtable, &TblEnumDeclaration_sub1},{DT_Token, {.mTokenId=94}},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblEnumDeclaration_sub2},{DT_Subtable, &TblEnumBody}};
RuleTable TblEnumDeclaration ={ET_Concatenate, RP_NA, 5, TblEnumDeclaration_data, 5, TblEnumDeclaration_action};
Action TblEnumBody_action[2] = {{ACT_BuildBlock,1,{2}},{ACT_AddToBlock,1,{4}}};
TableData TblEnumBody_sub1_data[1] ={{DT_Subtable, &TblEnumConstantList}};
RuleTable TblEnumBody_sub1 ={ET_Zeroorone, RP_NA, 1, TblEnumBody_sub1_data, 0, NULL};
TableData TblEnumBody_sub2_data[1] ={{DT_Token, {.mTokenId=44}}};
RuleTable TblEnumBody_sub2 ={ET_Zeroorone, RP_NA, 1, TblEnumBody_sub2_data, 0, NULL};
TableData TblEnumBody_sub3_data[1] ={{DT_Subtable, &TblEnumBodyDeclarations}};
RuleTable TblEnumBody_sub3 ={ET_Zeroorone, RP_NA, 1, TblEnumBody_sub3_data, 0, NULL};
TableData TblEnumBody_data[5] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblEnumBody_sub1},{DT_Subtable, &TblEnumBody_sub2},{DT_Subtable, &TblEnumBody_sub3},{DT_Token, {.mTokenId=48}}};
RuleTable TblEnumBody ={ET_Concatenate, RP_NA, 5, TblEnumBody_data, 2, TblEnumBody_action};
TableData TblEnumConstantList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblEnumConstant}};
RuleTable TblEnumConstantList_sub2 ={ET_Concatenate, RP_NA, 2, TblEnumConstantList_sub2_data, 0, NULL};
TableData TblEnumConstantList_sub1_data[1] ={{DT_Subtable, &TblEnumConstantList_sub2}};
RuleTable TblEnumConstantList_sub1 ={ET_Zeroormore, RP_NA, 1, TblEnumConstantList_sub1_data, 0, NULL};
TableData TblEnumConstantList_data[2] ={{DT_Subtable, &TblEnumConstant},{DT_Subtable, &TblEnumConstantList_sub1}};
RuleTable TblEnumConstantList ={ET_Concatenate, RP_NA, 2, TblEnumConstantList_data, 0, NULL};
Action TblEnumConstant_action[2] = {{ACT_AddInitTo,2,{2,3}},{ACT_AddInitTo,2,{2,4}}};
TableData TblEnumConstant_sub1_data[1] ={{DT_Subtable, &TblEnumConstantModifier}};
RuleTable TblEnumConstant_sub1 ={ET_Zeroormore, RP_NA, 1, TblEnumConstant_sub1_data, 0, NULL};
TableData TblEnumConstant_sub4_data[1] ={{DT_Subtable, &TblArgumentList}};
RuleTable TblEnumConstant_sub4 ={ET_Zeroorone, RP_NA, 1, TblEnumConstant_sub4_data, 0, NULL};
TableData TblEnumConstant_sub3_data[3] ={{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblEnumConstant_sub4},{DT_Token, {.mTokenId=50}}};
RuleTable TblEnumConstant_sub3 ={ET_Concatenate, RP_NA, 3, TblEnumConstant_sub3_data, 0, NULL};
TableData TblEnumConstant_sub2_data[1] ={{DT_Subtable, &TblEnumConstant_sub3}};
RuleTable TblEnumConstant_sub2 ={ET_Zeroorone, RP_NA, 1, TblEnumConstant_sub2_data, 0, NULL};
TableData TblEnumConstant_sub5_data[1] ={{DT_Subtable, &TblClassBody}};
RuleTable TblEnumConstant_sub5 ={ET_Zeroorone, RP_NA, 1, TblEnumConstant_sub5_data, 0, NULL};
TableData TblEnumConstant_data[4] ={{DT_Subtable, &TblEnumConstant_sub1},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblEnumConstant_sub2},{DT_Subtable, &TblEnumConstant_sub5}};
RuleTable TblEnumConstant ={ET_Concatenate, RP_NA, 4, TblEnumConstant_data, 2, TblEnumConstant_action};
TableData TblEnumConstantModifier_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblEnumConstantModifier ={ET_Data, RP_NA, 1, TblEnumConstantModifier_data, 0, NULL};
TableData TblEnumBodyDeclarations_sub1_data[1] ={{DT_Subtable, &TblClassBodyDeclaration}};
RuleTable TblEnumBodyDeclarations_sub1 ={ET_Zeroormore, RP_NA, 1, TblEnumBodyDeclarations_sub1_data, 0, NULL};
TableData TblEnumBodyDeclarations_data[2] ={{DT_Token, {.mTokenId=45}},{DT_Subtable, &TblEnumBodyDeclarations_sub1}};
RuleTable TblEnumBodyDeclarations ={ET_Concatenate, RP_NA, 2, TblEnumBodyDeclarations_data, 0, NULL};
TableData TblBlockStatement_data[3] ={{DT_Subtable, &TblLocalVariableDeclarationStatement},{DT_Subtable, &TblClassDeclaration},{DT_Subtable, &TblStatement}};
RuleTable TblBlockStatement ={ET_Oneof, RP_Single, 3, TblBlockStatement_data, 0, NULL};
TableData TblBlockStatements_sub1_data[1] ={{DT_Subtable, &TblBlockStatement}};
RuleTable TblBlockStatements_sub1 ={ET_Zeroormore, RP_NA, 1, TblBlockStatements_sub1_data, 0, NULL};
TableData TblBlockStatements_data[2] ={{DT_Subtable, &TblBlockStatement},{DT_Subtable, &TblBlockStatements_sub1}};
RuleTable TblBlockStatements ={ET_Concatenate, RP_NA, 2, TblBlockStatements_data, 0, NULL};
Action TblBlock_action[1] = {{ACT_BuildBlock,1,{2}}};
TableData TblBlock_sub1_data[1] ={{DT_Subtable, &TblBlockStatements}};
RuleTable TblBlock_sub1 ={ET_Zeroorone, RP_NA, 1, TblBlock_sub1_data, 0, NULL};
TableData TblBlock_data[3] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblBlock_sub1},{DT_Token, {.mTokenId=48}}};
RuleTable TblBlock ={ET_Concatenate, RP_NA, 3, TblBlock_data, 1, TblBlock_action};
TableData TblInterfaceDeclaration_data[2] ={{DT_Subtable, &TblNormalInterfaceDeclaration},{DT_Subtable, &TblAnnotationTypeDeclaration}};
RuleTable TblInterfaceDeclaration ={ET_Oneof, RP_Single, 2, TblInterfaceDeclaration_data, 0, NULL};
TableData TblNormalInterfaceDeclaration_sub1_data[1] ={{DT_Subtable, &TblInterfaceModifier}};
RuleTable TblNormalInterfaceDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblNormalInterfaceDeclaration_sub1_data, 0, NULL};
TableData TblNormalInterfaceDeclaration_sub2_data[1] ={{DT_Subtable, &TblTypeParameters}};
RuleTable TblNormalInterfaceDeclaration_sub2 ={ET_Zeroorone, RP_NA, 1, TblNormalInterfaceDeclaration_sub2_data, 0, NULL};
TableData TblNormalInterfaceDeclaration_sub3_data[1] ={{DT_Subtable, &TblExtendsInterfaces}};
RuleTable TblNormalInterfaceDeclaration_sub3 ={ET_Zeroorone, RP_NA, 1, TblNormalInterfaceDeclaration_sub3_data, 0, NULL};
TableData TblNormalInterfaceDeclaration_data[6] ={{DT_Subtable, &TblNormalInterfaceDeclaration_sub1},{DT_Token, {.mTokenId=58}},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblNormalInterfaceDeclaration_sub2},{DT_Subtable, &TblNormalInterfaceDeclaration_sub3},{DT_Subtable, &TblInterfaceBody}};
RuleTable TblNormalInterfaceDeclaration ={ET_Concatenate, RP_NA, 6, TblNormalInterfaceDeclaration_data, 0, NULL};
TableData TblInterfaceAttr_data[6] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=56}},{DT_Token, {.mTokenId=63}},{DT_Token, {.mTokenId=61}},{DT_Token, {.mTokenId=69}},{DT_Token, {.mTokenId=59}}};
RuleTable TblInterfaceAttr ={ET_Oneof, RP_Single, 6, TblInterfaceAttr_data, 0, NULL};
TableData TblInterfaceModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblInterfaceAttr}};
RuleTable TblInterfaceModifier ={ET_Oneof, RP_Single, 2, TblInterfaceModifier_data, 0, NULL};
TableData TblExtendsInterfaces_data[2] ={{DT_Token, {.mTokenId=64}},{DT_Subtable, &TblInterfaceTypeList}};
RuleTable TblExtendsInterfaces ={ET_Concatenate, RP_NA, 2, TblExtendsInterfaces_data, 0, NULL};
TableData TblInterfaceBody_sub1_data[1] ={{DT_Subtable, &TblInterfaceMemberDeclaration}};
RuleTable TblInterfaceBody_sub1 ={ET_Zeroormore, RP_NA, 1, TblInterfaceBody_sub1_data, 0, NULL};
TableData TblInterfaceBody_data[3] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblInterfaceBody_sub1},{DT_Token, {.mTokenId=48}}};
RuleTable TblInterfaceBody ={ET_Concatenate, RP_NA, 3, TblInterfaceBody_data, 0, NULL};
TableData TblInterfaceMemberDeclaration_data[5] ={{DT_Subtable, &TblConstantDeclaration},{DT_Subtable, &TblInterfaceMethodDeclaration},{DT_Subtable, &TblClassDeclaration},{DT_Subtable, &TblInterfaceDeclaration},{DT_Token, {.mTokenId=45}}};
RuleTable TblInterfaceMemberDeclaration ={ET_Oneof, RP_Single, 5, TblInterfaceMemberDeclaration_data, 0, NULL};
TableData TblConstantDeclaration_sub1_data[1] ={{DT_Subtable, &TblConstantModifier}};
RuleTable TblConstantDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblConstantDeclaration_sub1_data, 0, NULL};
TableData TblConstantDeclaration_data[4] ={{DT_Subtable, &TblConstantDeclaration_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblVariableDeclaratorList},{DT_Token, {.mTokenId=45}}};
RuleTable TblConstantDeclaration ={ET_Concatenate, RP_NA, 4, TblConstantDeclaration_data, 0, NULL};
TableData TblConstantAttr_data[3] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=69}},{DT_Token, {.mTokenId=78}}};
RuleTable TblConstantAttr ={ET_Oneof, RP_Single, 3, TblConstantAttr_data, 0, NULL};
TableData TblConstantModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblConstantAttr}};
RuleTable TblConstantModifier ={ET_Oneof, RP_Single, 2, TblConstantModifier_data, 0, NULL};
TableData TblInterfaceMethodDeclaration_sub1_data[1] ={{DT_Subtable, &TblInterfaceMethodModifier}};
RuleTable TblInterfaceMethodDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblInterfaceMethodDeclaration_sub1_data, 0, NULL};
TableData TblInterfaceMethodDeclaration_data[3] ={{DT_Subtable, &TblInterfaceMethodDeclaration_sub1},{DT_Subtable, &TblMethodHeader},{DT_Subtable, &TblMethodBody}};
RuleTable TblInterfaceMethodDeclaration ={ET_Concatenate, RP_NA, 3, TblInterfaceMethodDeclaration_data, 0, NULL};
TableData TblInterfaceMethodAttr_data[5] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=61}},{DT_Token, {.mTokenId=66}},{DT_Token, {.mTokenId=69}},{DT_Token, {.mTokenId=59}}};
RuleTable TblInterfaceMethodAttr ={ET_Oneof, RP_Single, 5, TblInterfaceMethodAttr_data, 0, NULL};
TableData TblInterfaceMethodModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblInterfaceMethodAttr}};
RuleTable TblInterfaceMethodModifier ={ET_Oneof, RP_Single, 2, TblInterfaceMethodModifier_data, 0, NULL};
Action TblAnnotationTypeDeclaration_action[3] = {{ACT_BuildAnnotationType,1,{4}},{ACT_AddModifier,1,{1}},{ACT_AddAnnotationTypeBody,1,{5}}};
TableData TblAnnotationTypeDeclaration_sub1_data[1] ={{DT_Subtable, &TblInterfaceModifier}};
RuleTable TblAnnotationTypeDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblAnnotationTypeDeclaration_sub1_data, 0, NULL};
TableData TblAnnotationTypeDeclaration_data[5] ={{DT_Subtable, &TblAnnotationTypeDeclaration_sub1},{DT_Token, {.mTokenId=41}},{DT_Token, {.mTokenId=58}},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblAnnotationTypeBody}};
RuleTable TblAnnotationTypeDeclaration ={ET_Concatenate, RP_NA, 5, TblAnnotationTypeDeclaration_data, 3, TblAnnotationTypeDeclaration_action};
Action TblAnnotationTypeBody_action[1] = {{ACT_BuildBlock,1,{2}}};
TableData TblAnnotationTypeBody_sub1_data[1] ={{DT_Subtable, &TblAnnotationTypeMemberDeclaration}};
RuleTable TblAnnotationTypeBody_sub1 ={ET_Zeroormore, RP_NA, 1, TblAnnotationTypeBody_sub1_data, 0, NULL};
TableData TblAnnotationTypeBody_data[3] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblAnnotationTypeBody_sub1},{DT_Token, {.mTokenId=48}}};
RuleTable TblAnnotationTypeBody ={ET_Concatenate, RP_NA, 3, TblAnnotationTypeBody_data, 1, TblAnnotationTypeBody_action};
TableData TblAnnotationTypeMemberDeclaration_data[5] ={{DT_Subtable, &TblAnnotationTypeElementDeclaration},{DT_Subtable, &TblConstantDeclaration},{DT_Subtable, &TblClassDeclaration},{DT_Subtable, &TblInterfaceDeclaration},{DT_Token, {.mTokenId=45}}};
RuleTable TblAnnotationTypeMemberDeclaration ={ET_Oneof, RP_Single, 5, TblAnnotationTypeMemberDeclaration_data, 0, NULL};
TableData TblAnnotationTypeElementDeclaration_sub1_data[1] ={{DT_Subtable, &TblAnnotationTypeElementModifier}};
RuleTable TblAnnotationTypeElementDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblAnnotationTypeElementDeclaration_sub1_data, 0, NULL};
TableData TblAnnotationTypeElementDeclaration_sub2_data[1] ={{DT_Subtable, &TblDims}};
RuleTable TblAnnotationTypeElementDeclaration_sub2 ={ET_Zeroorone, RP_NA, 1, TblAnnotationTypeElementDeclaration_sub2_data, 0, NULL};
TableData TblAnnotationTypeElementDeclaration_sub3_data[1] ={{DT_Subtable, &TblDefaultValue}};
RuleTable TblAnnotationTypeElementDeclaration_sub3 ={ET_Zeroorone, RP_NA, 1, TblAnnotationTypeElementDeclaration_sub3_data, 0, NULL};
TableData TblAnnotationTypeElementDeclaration_data[8] ={{DT_Subtable, &TblAnnotationTypeElementDeclaration_sub1},{DT_Subtable, &TblUnannType},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=51}},{DT_Token, {.mTokenId=50}},{DT_Subtable, &TblAnnotationTypeElementDeclaration_sub2},{DT_Subtable, &TblAnnotationTypeElementDeclaration_sub3},{DT_Token, {.mTokenId=45}}};
RuleTable TblAnnotationTypeElementDeclaration ={ET_Concatenate, RP_NA, 8, TblAnnotationTypeElementDeclaration_data, 0, NULL};
TableData TblAnnotationTypeElementAttr_data[2] ={{DT_Token, {.mTokenId=70}},{DT_Token, {.mTokenId=61}}};
RuleTable TblAnnotationTypeElementAttr ={ET_Oneof, RP_Single, 2, TblAnnotationTypeElementAttr_data, 0, NULL};
TableData TblAnnotationTypeElementModifier_data[2] ={{DT_Subtable, &TblAnnotation},{DT_Subtable, &TblAnnotationTypeElementAttr}};
RuleTable TblAnnotationTypeElementModifier ={ET_Oneof, RP_Single, 2, TblAnnotationTypeElementModifier_data, 0, NULL};
TableData TblDefaultValue_data[2] ={{DT_Token, {.mTokenId=66}},{DT_Subtable, &TblElementValue}};
RuleTable TblDefaultValue ={ET_Concatenate, RP_NA, 2, TblDefaultValue_data, 0, NULL};
TableData TblAnnotation_data[3] ={{DT_Subtable, &TblNormalAnnotation},{DT_Subtable, &TblMarkerAnnotation},{DT_Subtable, &TblSingleElementAnnotation}};
RuleTable TblAnnotation ={ET_Oneof, RP_Single, 3, TblAnnotation_data, 0, NULL};
Action TblNormalAnnotation_action[1] = {{ACT_BuildAnnotation,1,{2}}};
TableData TblNormalAnnotation_sub1_data[1] ={{DT_Subtable, &TblElementValuePairList}};
RuleTable TblNormalAnnotation_sub1 ={ET_Zeroorone, RP_NA, 1, TblNormalAnnotation_sub1_data, 0, NULL};
TableData TblNormalAnnotation_data[5] ={{DT_Token, {.mTokenId=41}},{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblNormalAnnotation_sub1},{DT_Token, {.mTokenId=50}}};
RuleTable TblNormalAnnotation ={ET_Concatenate, RP_NA, 5, TblNormalAnnotation_data, 1, TblNormalAnnotation_action};
Action TblMarkerAnnotation_action[1] = {{ACT_BuildAnnotation,1,{2}}};
TableData TblMarkerAnnotation_data[2] ={{DT_Token, {.mTokenId=41}},{DT_Subtable, &TblTypeName}};
RuleTable TblMarkerAnnotation ={ET_Concatenate, RP_NA, 2, TblMarkerAnnotation_data, 1, TblMarkerAnnotation_action};
Action TblSingleElementAnnotation_action[1] = {{ACT_BuildAnnotation,1,{2}}};
TableData TblSingleElementAnnotation_data[5] ={{DT_Token, {.mTokenId=41}},{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=51}},{DT_Subtable, &TblElementValue},{DT_Token, {.mTokenId=50}}};
RuleTable TblSingleElementAnnotation ={ET_Concatenate, RP_NA, 5, TblSingleElementAnnotation_data, 1, TblSingleElementAnnotation_action};
TableData TblElementValuePairList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblElementValuePair}};
RuleTable TblElementValuePairList_sub2 ={ET_Concatenate, RP_NA, 2, TblElementValuePairList_sub2_data, 0, NULL};
TableData TblElementValuePairList_sub1_data[1] ={{DT_Subtable, &TblElementValuePairList_sub2}};
RuleTable TblElementValuePairList_sub1 ={ET_Zeroormore, RP_NA, 1, TblElementValuePairList_sub1_data, 0, NULL};
TableData TblElementValuePairList_data[2] ={{DT_Subtable, &TblElementValuePair},{DT_Subtable, &TblElementValuePairList_sub1}};
RuleTable TblElementValuePairList ={ET_Concatenate, RP_NA, 2, TblElementValuePairList_data, 0, NULL};
TableData TblElementValuePair_data[3] ={{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=25}},{DT_Subtable, &TblElementValue}};
RuleTable TblElementValuePair ={ET_Concatenate, RP_NA, 3, TblElementValuePair_data, 0, NULL};
TableData TblElementValue_data[3] ={{DT_Subtable, &TblConditionalExpression},{DT_Subtable, &TblElementValueArrayInitializer},{DT_Subtable, &TblAnnotation}};
RuleTable TblElementValue ={ET_Oneof, RP_NA, 3, TblElementValue_data, 0, NULL};
TableData TblElementValueArrayInitializer_sub1_data[1] ={{DT_Subtable, &TblElementValueList}};
RuleTable TblElementValueArrayInitializer_sub1 ={ET_Zeroorone, RP_NA, 1, TblElementValueArrayInitializer_sub1_data, 0, NULL};
TableData TblElementValueArrayInitializer_sub2_data[1] ={{DT_Token, {.mTokenId=44}}};
RuleTable TblElementValueArrayInitializer_sub2 ={ET_Zeroorone, RP_NA, 1, TblElementValueArrayInitializer_sub2_data, 0, NULL};
TableData TblElementValueArrayInitializer_data[4] ={{DT_Token, {.mTokenId=49}},{DT_Subtable, &TblElementValueArrayInitializer_sub1},{DT_Subtable, &TblElementValueArrayInitializer_sub2},{DT_Token, {.mTokenId=48}}};
RuleTable TblElementValueArrayInitializer ={ET_Concatenate, RP_NA, 4, TblElementValueArrayInitializer_data, 0, NULL};
TableData TblElementValueList_sub2_data[2] ={{DT_Token, {.mTokenId=44}},{DT_Subtable, &TblElementValue}};
RuleTable TblElementValueList_sub2 ={ET_Concatenate, RP_NA, 2, TblElementValueList_sub2_data, 0, NULL};
TableData TblElementValueList_sub1_data[1] ={{DT_Subtable, &TblElementValueList_sub2}};
RuleTable TblElementValueList_sub1 ={ET_Zeroormore, RP_NA, 1, TblElementValueList_sub1_data, 0, NULL};
TableData TblElementValueList_data[2] ={{DT_Subtable, &TblElementValue},{DT_Subtable, &TblElementValueList_sub1}};
RuleTable TblElementValueList ={ET_Concatenate, RP_NA, 2, TblElementValueList_data, 0, NULL};
TableData TblPackageModifier_data[1] ={{DT_Subtable, &TblAnnotation}};
RuleTable TblPackageModifier ={ET_Data, RP_NA, 1, TblPackageModifier_data, 0, NULL};
Action TblPackageDeclaration_action[2] = {{ACT_BuildField,2,{3,4}},{ACT_BuildPackageName,0,{}}};
TableData TblPackageDeclaration_sub1_data[1] ={{DT_Subtable, &TblPackageModifier}};
RuleTable TblPackageDeclaration_sub1 ={ET_Zeroormore, RP_NA, 1, TblPackageDeclaration_sub1_data, 0, NULL};
TableData TblPackageDeclaration_sub3_data[2] ={{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier}};
RuleTable TblPackageDeclaration_sub3 ={ET_Concatenate, RP_NA, 2, TblPackageDeclaration_sub3_data, 0, NULL};
TableData TblPackageDeclaration_sub2_data[1] ={{DT_Subtable, &TblPackageDeclaration_sub3}};
RuleTable TblPackageDeclaration_sub2 ={ET_Zeroormore, RP_NA, 1, TblPackageDeclaration_sub2_data, 0, NULL};
TableData TblPackageDeclaration_data[5] ={{DT_Subtable, &TblPackageDeclaration_sub1},{DT_Token, {.mTokenId=67}},{DT_Subtable, &TblIdentifier},{DT_Subtable, &TblPackageDeclaration_sub2},{DT_Token, {.mTokenId=45}}};
RuleTable TblPackageDeclaration ={ET_Concatenate, RP_NA, 5, TblPackageDeclaration_data, 2, TblPackageDeclaration_action};
TableData TblImportDeclaration_data[4] ={{DT_Subtable, &TblSingleTypeImportDeclaration},{DT_Subtable, &TblTypeImportOnDemandDeclaration},{DT_Subtable, &TblSingleStaticImportDeclaration},{DT_Subtable, &TblStaticImportOnDemandDeclaration}};
RuleTable TblImportDeclaration ={ET_Oneof, RP_NA, 4, TblImportDeclaration_data, 0, NULL};
Action TblSingleTypeImportDeclaration_action[1] = {{ACT_BuildSingleTypeImport,1,{2}}};
TableData TblSingleTypeImportDeclaration_data[3] ={{DT_Token, {.mTokenId=73}},{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=45}}};
RuleTable TblSingleTypeImportDeclaration ={ET_Concatenate, RP_NA, 3, TblSingleTypeImportDeclaration_data, 1, TblSingleTypeImportDeclaration_action};
Action TblTypeImportOnDemandDeclaration_action[1] = {{ACT_BuildAllTypeImport,1,{2}}};
TableData TblTypeImportOnDemandDeclaration_data[5] ={{DT_Token, {.mTokenId=73}},{DT_Subtable, &TblPackageOrTypeName},{DT_Token, {.mTokenId=43}},{DT_Token, {.mTokenId=35}},{DT_Token, {.mTokenId=45}}};
RuleTable TblTypeImportOnDemandDeclaration ={ET_Concatenate, RP_NA, 5, TblTypeImportOnDemandDeclaration_data, 1, TblTypeImportOnDemandDeclaration_action};
Action TblSingleStaticImportDeclaration_action[1] = {{ACT_BuildSingleStaticImport,2,{3,4}}};
TableData TblSingleStaticImportDeclaration_data[6] ={{DT_Token, {.mTokenId=73}},{DT_Token, {.mTokenId=69}},{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblIdentifier},{DT_Token, {.mTokenId=45}}};
RuleTable TblSingleStaticImportDeclaration ={ET_Concatenate, RP_NA, 6, TblSingleStaticImportDeclaration_data, 1, TblSingleStaticImportDeclaration_action};
Action TblStaticImportOnDemandDeclaration_action[1] = {{ACT_BuildAllStaticImport,1,{3}}};
TableData TblStaticImportOnDemandDeclaration_data[6] ={{DT_Token, {.mTokenId=73}},{DT_Token, {.mTokenId=69}},{DT_Subtable, &TblTypeName},{DT_Token, {.mTokenId=43}},{DT_Token, {.mTokenId=35}},{DT_Token, {.mTokenId=45}}};
RuleTable TblStaticImportOnDemandDeclaration ={ET_Concatenate, RP_NA, 6, TblStaticImportOnDemandDeclaration_data, 1, TblStaticImportOnDemandDeclaration_action};
