#include "common_header_autogen.h"
TableData TblNonZeroDigit_data[9] ={{DT_Char, {.mChar='1'}},{DT_Char, {.mChar='2'}},{DT_Char, {.mChar='3'}},{DT_Char, {.mChar='4'}},{DT_Char, {.mChar='5'}},{DT_Char, {.mChar='6'}},{DT_Char, {.mChar='7'}},{DT_Char, {.mChar='8'}},{DT_Char, {.mChar='9'}}};
RuleTable TblNonZeroDigit ={ET_Oneof, RP_NA, 9, TblNonZeroDigit_data, 0, NULL};
TableData TblUnderscores_sub1_data[1] ={{DT_Char, {.mChar='_'}}};
RuleTable TblUnderscores_sub1 ={ET_Zeroormore, RP_NA, 1, TblUnderscores_sub1_data, 0, NULL};
TableData TblUnderscores_data[2] ={{DT_Char, {.mChar='_'}},{DT_Subtable, &TblUnderscores_sub1}};
RuleTable TblUnderscores ={ET_Concatenate, RP_NA, 2, TblUnderscores_data, 0, NULL};
TableData TblDigit_data[2] ={{DT_Char, {.mChar='0'}},{DT_Subtable, &TblNonZeroDigit}};
RuleTable TblDigit ={ET_Oneof, RP_NA, 2, TblDigit_data, 0, NULL};
TableData TblDigitOrUnderscore_data[2] ={{DT_Subtable, &TblDigit},{DT_Char, {.mChar='_'}}};
RuleTable TblDigitOrUnderscore ={ET_Oneof, RP_NA, 2, TblDigitOrUnderscore_data, 0, NULL};
TableData TblDigitsAndUnderscores_sub1_data[1] ={{DT_Subtable, &TblDigitOrUnderscore}};
RuleTable TblDigitsAndUnderscores_sub1 ={ET_Zeroormore, RP_NA, 1, TblDigitsAndUnderscores_sub1_data, 0, NULL};
TableData TblDigitsAndUnderscores_data[2] ={{DT_Subtable, &TblDigitOrUnderscore},{DT_Subtable, &TblDigitsAndUnderscores_sub1}};
RuleTable TblDigitsAndUnderscores ={ET_Concatenate, RP_NA, 2, TblDigitsAndUnderscores_data, 0, NULL};
TableData TblDigits_sub2_data[1] ={{DT_Subtable, &TblDigitsAndUnderscores}};
RuleTable TblDigits_sub2 ={ET_Zeroorone, RP_NA, 1, TblDigits_sub2_data, 0, NULL};
TableData TblDigits_sub1_data[3] ={{DT_Subtable, &TblDigit},{DT_Subtable, &TblDigits_sub2},{DT_Subtable, &TblDigit}};
RuleTable TblDigits_sub1 ={ET_Concatenate, RP_NA, 3, TblDigits_sub1_data, 0, NULL};
TableData TblDigits_data[2] ={{DT_Subtable, &TblDigit},{DT_Subtable, &TblDigits_sub1}};
RuleTable TblDigits ={ET_Oneof, RP_NA, 2, TblDigits_data, 0, NULL};
TableData TblDecimalNumeral_sub2_data[1] ={{DT_Subtable, &TblDigits}};
RuleTable TblDecimalNumeral_sub2 ={ET_Zeroorone, RP_NA, 1, TblDecimalNumeral_sub2_data, 0, NULL};
TableData TblDecimalNumeral_sub1_data[2] ={{DT_Subtable, &TblNonZeroDigit},{DT_Subtable, &TblDecimalNumeral_sub2}};
RuleTable TblDecimalNumeral_sub1 ={ET_Concatenate, RP_NA, 2, TblDecimalNumeral_sub1_data, 0, NULL};
TableData TblDecimalNumeral_sub3_data[3] ={{DT_Subtable, &TblNonZeroDigit},{DT_Subtable, &TblUnderscores},{DT_Subtable, &TblDigits}};
RuleTable TblDecimalNumeral_sub3 ={ET_Concatenate, RP_NA, 3, TblDecimalNumeral_sub3_data, 0, NULL};
TableData TblDecimalNumeral_data[3] ={{DT_Char, {.mChar='0'}},{DT_Subtable, &TblDecimalNumeral_sub1},{DT_Subtable, &TblDecimalNumeral_sub3}};
RuleTable TblDecimalNumeral ={ET_Oneof, RP_NA, 3, TblDecimalNumeral_data, 0, NULL};
TableData TblHexDigit_data[22] ={{DT_Char, {.mChar='0'}},{DT_Char, {.mChar='1'}},{DT_Char, {.mChar='2'}},{DT_Char, {.mChar='3'}},{DT_Char, {.mChar='4'}},{DT_Char, {.mChar='5'}},{DT_Char, {.mChar='6'}},{DT_Char, {.mChar='7'}},{DT_Char, {.mChar='8'}},{DT_Char, {.mChar='9'}},{DT_Char, {.mChar='a'}},{DT_Char, {.mChar='b'}},{DT_Char, {.mChar='c'}},{DT_Char, {.mChar='d'}},{DT_Char, {.mChar='e'}},{DT_Char, {.mChar='f'}},{DT_Char, {.mChar='A'}},{DT_Char, {.mChar='B'}},{DT_Char, {.mChar='C'}},{DT_Char, {.mChar='D'}},{DT_Char, {.mChar='E'}},{DT_Char, {.mChar='F'}}};
RuleTable TblHexDigit ={ET_Oneof, RP_NA, 22, TblHexDigit_data, 0, NULL};
TableData TblHexDigitOrUnderscore_data[2] ={{DT_Subtable, &TblHexDigit},{DT_Char, {.mChar='_'}}};
RuleTable TblHexDigitOrUnderscore ={ET_Oneof, RP_NA, 2, TblHexDigitOrUnderscore_data, 0, NULL};
TableData TblHexDigitsAndUnderscores_sub1_data[1] ={{DT_Subtable, &TblHexDigitOrUnderscore}};
RuleTable TblHexDigitsAndUnderscores_sub1 ={ET_Zeroormore, RP_NA, 1, TblHexDigitsAndUnderscores_sub1_data, 0, NULL};
TableData TblHexDigitsAndUnderscores_data[2] ={{DT_Subtable, &TblHexDigitOrUnderscore},{DT_Subtable, &TblHexDigitsAndUnderscores_sub1}};
RuleTable TblHexDigitsAndUnderscores ={ET_Concatenate, RP_NA, 2, TblHexDigitsAndUnderscores_data, 0, NULL};
TableData TblHexDigits_sub2_data[1] ={{DT_Subtable, &TblHexDigitsAndUnderscores}};
RuleTable TblHexDigits_sub2 ={ET_Zeroorone, RP_NA, 1, TblHexDigits_sub2_data, 0, NULL};
TableData TblHexDigits_sub1_data[3] ={{DT_Subtable, &TblHexDigit},{DT_Subtable, &TblHexDigits_sub2},{DT_Subtable, &TblHexDigit}};
RuleTable TblHexDigits_sub1 ={ET_Concatenate, RP_NA, 3, TblHexDigits_sub1_data, 0, NULL};
TableData TblHexDigits_data[2] ={{DT_Subtable, &TblHexDigit},{DT_Subtable, &TblHexDigits_sub1}};
RuleTable TblHexDigits ={ET_Oneof, RP_NA, 2, TblHexDigits_data, 0, NULL};
TableData TblHexNumeral_sub1_data[2] ={{DT_String, {.mString="0x"}},{DT_Subtable, &TblHexDigits}};
RuleTable TblHexNumeral_sub1 ={ET_Concatenate, RP_NA, 2, TblHexNumeral_sub1_data, 0, NULL};
TableData TblHexNumeral_sub2_data[2] ={{DT_String, {.mString="0X"}},{DT_Subtable, &TblHexDigits}};
RuleTable TblHexNumeral_sub2 ={ET_Concatenate, RP_NA, 2, TblHexNumeral_sub2_data, 0, NULL};
TableData TblHexNumeral_data[2] ={{DT_Subtable, &TblHexNumeral_sub1},{DT_Subtable, &TblHexNumeral_sub2}};
RuleTable TblHexNumeral ={ET_Oneof, RP_NA, 2, TblHexNumeral_data, 0, NULL};
TableData TblOctalDigit_data[8] ={{DT_Char, {.mChar='0'}},{DT_Char, {.mChar='1'}},{DT_Char, {.mChar='2'}},{DT_Char, {.mChar='3'}},{DT_Char, {.mChar='4'}},{DT_Char, {.mChar='5'}},{DT_Char, {.mChar='6'}},{DT_Char, {.mChar='7'}}};
RuleTable TblOctalDigit ={ET_Oneof, RP_NA, 8, TblOctalDigit_data, 0, NULL};
TableData TblOctalDigitOrUnderscore_data[2] ={{DT_Subtable, &TblOctalDigit},{DT_Char, {.mChar='_'}}};
RuleTable TblOctalDigitOrUnderscore ={ET_Oneof, RP_NA, 2, TblOctalDigitOrUnderscore_data, 0, NULL};
TableData TblOctalDigitsAndUnderscores_sub1_data[1] ={{DT_Subtable, &TblOctalDigitOrUnderscore}};
RuleTable TblOctalDigitsAndUnderscores_sub1 ={ET_Zeroormore, RP_NA, 1, TblOctalDigitsAndUnderscores_sub1_data, 0, NULL};
TableData TblOctalDigitsAndUnderscores_data[2] ={{DT_Subtable, &TblOctalDigitOrUnderscore},{DT_Subtable, &TblOctalDigitsAndUnderscores_sub1}};
RuleTable TblOctalDigitsAndUnderscores ={ET_Concatenate, RP_NA, 2, TblOctalDigitsAndUnderscores_data, 0, NULL};
TableData TblOctalDigits_sub2_data[1] ={{DT_Subtable, &TblOctalDigitsAndUnderscores}};
RuleTable TblOctalDigits_sub2 ={ET_Zeroorone, RP_NA, 1, TblOctalDigits_sub2_data, 0, NULL};
TableData TblOctalDigits_sub1_data[3] ={{DT_Subtable, &TblOctalDigit},{DT_Subtable, &TblOctalDigits_sub2},{DT_Subtable, &TblOctalDigit}};
RuleTable TblOctalDigits_sub1 ={ET_Concatenate, RP_NA, 3, TblOctalDigits_sub1_data, 0, NULL};
TableData TblOctalDigits_data[2] ={{DT_Subtable, &TblOctalDigit},{DT_Subtable, &TblOctalDigits_sub1}};
RuleTable TblOctalDigits ={ET_Oneof, RP_NA, 2, TblOctalDigits_data, 0, NULL};
TableData TblOctalNumeral_sub1_data[2] ={{DT_Char, {.mChar='0'}},{DT_Subtable, &TblOctalDigits}};
RuleTable TblOctalNumeral_sub1 ={ET_Concatenate, RP_NA, 2, TblOctalNumeral_sub1_data, 0, NULL};
TableData TblOctalNumeral_sub2_data[3] ={{DT_Char, {.mChar='0'}},{DT_Subtable, &TblUnderscores},{DT_Subtable, &TblOctalDigits}};
RuleTable TblOctalNumeral_sub2 ={ET_Concatenate, RP_NA, 3, TblOctalNumeral_sub2_data, 0, NULL};
TableData TblOctalNumeral_data[2] ={{DT_Subtable, &TblOctalNumeral_sub1},{DT_Subtable, &TblOctalNumeral_sub2}};
RuleTable TblOctalNumeral ={ET_Oneof, RP_NA, 2, TblOctalNumeral_data, 0, NULL};
TableData TblBinDigit_data[2] ={{DT_Char, {.mChar='0'}},{DT_Char, {.mChar='1'}}};
RuleTable TblBinDigit ={ET_Oneof, RP_NA, 2, TblBinDigit_data, 0, NULL};
TableData TblBinDigitOrUnderscore_data[2] ={{DT_Subtable, &TblBinDigit},{DT_Char, {.mChar='_'}}};
RuleTable TblBinDigitOrUnderscore ={ET_Oneof, RP_NA, 2, TblBinDigitOrUnderscore_data, 0, NULL};
TableData TblBinDigitsAndUnderscores_sub1_data[1] ={{DT_Subtable, &TblBinDigitOrUnderscore}};
RuleTable TblBinDigitsAndUnderscores_sub1 ={ET_Zeroormore, RP_NA, 1, TblBinDigitsAndUnderscores_sub1_data, 0, NULL};
TableData TblBinDigitsAndUnderscores_data[2] ={{DT_Subtable, &TblBinDigitOrUnderscore},{DT_Subtable, &TblBinDigitsAndUnderscores_sub1}};
RuleTable TblBinDigitsAndUnderscores ={ET_Concatenate, RP_NA, 2, TblBinDigitsAndUnderscores_data, 0, NULL};
TableData TblBinDigits_sub2_data[1] ={{DT_Subtable, &TblBinDigitsAndUnderscores}};
RuleTable TblBinDigits_sub2 ={ET_Zeroorone, RP_NA, 1, TblBinDigits_sub2_data, 0, NULL};
TableData TblBinDigits_sub1_data[3] ={{DT_Subtable, &TblBinDigit},{DT_Subtable, &TblBinDigits_sub2},{DT_Subtable, &TblBinDigit}};
RuleTable TblBinDigits_sub1 ={ET_Concatenate, RP_NA, 3, TblBinDigits_sub1_data, 0, NULL};
TableData TblBinDigits_data[2] ={{DT_Subtable, &TblBinDigit},{DT_Subtable, &TblBinDigits_sub1}};
RuleTable TblBinDigits ={ET_Oneof, RP_NA, 2, TblBinDigits_data, 0, NULL};
TableData TblBinNumeral_sub1_data[2] ={{DT_String, {.mString="0b"}},{DT_Subtable, &TblBinDigits}};
RuleTable TblBinNumeral_sub1 ={ET_Concatenate, RP_NA, 2, TblBinNumeral_sub1_data, 0, NULL};
TableData TblBinNumeral_sub2_data[2] ={{DT_String, {.mString="0B"}},{DT_Subtable, &TblBinDigits}};
RuleTable TblBinNumeral_sub2 ={ET_Concatenate, RP_NA, 2, TblBinNumeral_sub2_data, 0, NULL};
TableData TblBinNumeral_data[2] ={{DT_Subtable, &TblBinNumeral_sub1},{DT_Subtable, &TblBinNumeral_sub2}};
RuleTable TblBinNumeral ={ET_Oneof, RP_NA, 2, TblBinNumeral_data, 0, NULL};
TableData TblIntegerTypeSuffix_data[2] ={{DT_Char, {.mChar='L'}},{DT_Char, {.mChar='l'}}};
RuleTable TblIntegerTypeSuffix ={ET_Oneof, RP_NA, 2, TblIntegerTypeSuffix_data, 0, NULL};
TableData TblDecimalIntegerLiteral_sub1_data[1] ={{DT_Subtable, &TblIntegerTypeSuffix}};
RuleTable TblDecimalIntegerLiteral_sub1 ={ET_Zeroorone, RP_NA, 1, TblDecimalIntegerLiteral_sub1_data, 0, NULL};
TableData TblDecimalIntegerLiteral_data[2] ={{DT_Subtable, &TblDecimalNumeral},{DT_Subtable, &TblDecimalIntegerLiteral_sub1}};
RuleTable TblDecimalIntegerLiteral ={ET_Concatenate, RP_NA, 2, TblDecimalIntegerLiteral_data, 0, NULL};
TableData TblHexIntegerLiteral_sub1_data[1] ={{DT_Subtable, &TblIntegerTypeSuffix}};
RuleTable TblHexIntegerLiteral_sub1 ={ET_Zeroorone, RP_NA, 1, TblHexIntegerLiteral_sub1_data, 0, NULL};
TableData TblHexIntegerLiteral_data[2] ={{DT_Subtable, &TblHexNumeral},{DT_Subtable, &TblHexIntegerLiteral_sub1}};
RuleTable TblHexIntegerLiteral ={ET_Concatenate, RP_NA, 2, TblHexIntegerLiteral_data, 0, NULL};
TableData TblOctalIntegerLiteral_sub1_data[1] ={{DT_Subtable, &TblIntegerTypeSuffix}};
RuleTable TblOctalIntegerLiteral_sub1 ={ET_Zeroorone, RP_NA, 1, TblOctalIntegerLiteral_sub1_data, 0, NULL};
TableData TblOctalIntegerLiteral_data[2] ={{DT_Subtable, &TblOctalNumeral},{DT_Subtable, &TblOctalIntegerLiteral_sub1}};
RuleTable TblOctalIntegerLiteral ={ET_Concatenate, RP_NA, 2, TblOctalIntegerLiteral_data, 0, NULL};
TableData TblBinaryIntegerLiteral_sub1_data[1] ={{DT_Subtable, &TblIntegerTypeSuffix}};
RuleTable TblBinaryIntegerLiteral_sub1 ={ET_Zeroorone, RP_NA, 1, TblBinaryIntegerLiteral_sub1_data, 0, NULL};
TableData TblBinaryIntegerLiteral_data[2] ={{DT_Subtable, &TblBinNumeral},{DT_Subtable, &TblBinaryIntegerLiteral_sub1}};
RuleTable TblBinaryIntegerLiteral ={ET_Concatenate, RP_NA, 2, TblBinaryIntegerLiteral_data, 0, NULL};
TableData TblIntegerLiteral_data[4] ={{DT_Subtable, &TblDecimalIntegerLiteral},{DT_Subtable, &TblHexIntegerLiteral},{DT_Subtable, &TblOctalIntegerLiteral},{DT_Subtable, &TblBinaryIntegerLiteral}};
RuleTable TblIntegerLiteral ={ET_Oneof, RP_NA, 4, TblIntegerLiteral_data, 0, NULL};
TableData TblSign_data[2] ={{DT_Token, {.mTokenId=37}},{DT_Token, {.mTokenId=36}}};
RuleTable TblSign ={ET_Oneof, RP_NA, 2, TblSign_data, 0, NULL};
TableData TblFloatTypeSuffix_data[4] ={{DT_Char, {.mChar='f'}},{DT_Char, {.mChar='F'}},{DT_Char, {.mChar='d'}},{DT_Char, {.mChar='D'}}};
RuleTable TblFloatTypeSuffix ={ET_Oneof, RP_NA, 4, TblFloatTypeSuffix_data, 0, NULL};
TableData TblExponentIndicator_data[2] ={{DT_Char, {.mChar='e'}},{DT_Char, {.mChar='E'}}};
RuleTable TblExponentIndicator ={ET_Oneof, RP_NA, 2, TblExponentIndicator_data, 0, NULL};
TableData TblSignedInteger_sub1_data[1] ={{DT_Subtable, &TblSign}};
RuleTable TblSignedInteger_sub1 ={ET_Zeroorone, RP_NA, 1, TblSignedInteger_sub1_data, 0, NULL};
TableData TblSignedInteger_data[2] ={{DT_Subtable, &TblSignedInteger_sub1},{DT_Subtable, &TblDigits}};
RuleTable TblSignedInteger ={ET_Concatenate, RP_NA, 2, TblSignedInteger_data, 0, NULL};
TableData TblExponentPart_data[2] ={{DT_Subtable, &TblExponentIndicator},{DT_Subtable, &TblSignedInteger}};
RuleTable TblExponentPart ={ET_Concatenate, RP_NA, 2, TblExponentPart_data, 0, NULL};
TableData TblDecFPLiteral_sub2_data[1] ={{DT_Subtable, &TblDigits}};
RuleTable TblDecFPLiteral_sub2 ={ET_Zeroorone, RP_NA, 1, TblDecFPLiteral_sub2_data, 0, NULL};
TableData TblDecFPLiteral_sub3_data[1] ={{DT_Subtable, &TblExponentPart}};
RuleTable TblDecFPLiteral_sub3 ={ET_Zeroorone, RP_NA, 1, TblDecFPLiteral_sub3_data, 0, NULL};
TableData TblDecFPLiteral_sub4_data[1] ={{DT_Subtable, &TblFloatTypeSuffix}};
RuleTable TblDecFPLiteral_sub4 ={ET_Zeroorone, RP_NA, 1, TblDecFPLiteral_sub4_data, 0, NULL};
TableData TblDecFPLiteral_sub1_data[5] ={{DT_Subtable, &TblDigits},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblDecFPLiteral_sub2},{DT_Subtable, &TblDecFPLiteral_sub3},{DT_Subtable, &TblDecFPLiteral_sub4}};
RuleTable TblDecFPLiteral_sub1 ={ET_Concatenate, RP_NA, 5, TblDecFPLiteral_sub1_data, 0, NULL};
TableData TblDecFPLiteral_sub6_data[1] ={{DT_Subtable, &TblExponentPart}};
RuleTable TblDecFPLiteral_sub6 ={ET_Zeroorone, RP_NA, 1, TblDecFPLiteral_sub6_data, 0, NULL};
TableData TblDecFPLiteral_sub7_data[1] ={{DT_Subtable, &TblFloatTypeSuffix}};
RuleTable TblDecFPLiteral_sub7 ={ET_Zeroorone, RP_NA, 1, TblDecFPLiteral_sub7_data, 0, NULL};
TableData TblDecFPLiteral_sub5_data[4] ={{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblDigits},{DT_Subtable, &TblDecFPLiteral_sub6},{DT_Subtable, &TblDecFPLiteral_sub7}};
RuleTable TblDecFPLiteral_sub5 ={ET_Concatenate, RP_NA, 4, TblDecFPLiteral_sub5_data, 0, NULL};
TableData TblDecFPLiteral_sub9_data[1] ={{DT_Subtable, &TblFloatTypeSuffix}};
RuleTable TblDecFPLiteral_sub9 ={ET_Zeroorone, RP_NA, 1, TblDecFPLiteral_sub9_data, 0, NULL};
TableData TblDecFPLiteral_sub8_data[3] ={{DT_Subtable, &TblDigits},{DT_Subtable, &TblExponentPart},{DT_Subtable, &TblDecFPLiteral_sub9}};
RuleTable TblDecFPLiteral_sub8 ={ET_Concatenate, RP_NA, 3, TblDecFPLiteral_sub8_data, 0, NULL};
TableData TblDecFPLiteral_sub11_data[1] ={{DT_Subtable, &TblExponentPart}};
RuleTable TblDecFPLiteral_sub11 ={ET_Zeroorone, RP_NA, 1, TblDecFPLiteral_sub11_data, 0, NULL};
TableData TblDecFPLiteral_sub10_data[2] ={{DT_Subtable, &TblDigits},{DT_Subtable, &TblDecFPLiteral_sub11}};
RuleTable TblDecFPLiteral_sub10 ={ET_Concatenate, RP_NA, 2, TblDecFPLiteral_sub10_data, 0, NULL};
TableData TblDecFPLiteral_data[4] ={{DT_Subtable, &TblDecFPLiteral_sub1},{DT_Subtable, &TblDecFPLiteral_sub5},{DT_Subtable, &TblDecFPLiteral_sub8},{DT_Subtable, &TblDecFPLiteral_sub10}};
RuleTable TblDecFPLiteral ={ET_Oneof, RP_NA, 4, TblDecFPLiteral_data, 0, NULL};
TableData TblBinaryExponentIndicator_data[2] ={{DT_Char, {.mChar='p'}},{DT_Char, {.mChar='P'}}};
RuleTable TblBinaryExponentIndicator ={ET_Oneof, RP_NA, 2, TblBinaryExponentIndicator_data, 0, NULL};
TableData TblBinaryExponent_data[2] ={{DT_Subtable, &TblBinaryExponentIndicator},{DT_Subtable, &TblSignedInteger}};
RuleTable TblBinaryExponent ={ET_Concatenate, RP_NA, 2, TblBinaryExponent_data, 0, NULL};
TableData TblHexSignificand_sub2_data[1] ={{DT_Token, {.mTokenId=43}}};
RuleTable TblHexSignificand_sub2 ={ET_Zeroorone, RP_NA, 1, TblHexSignificand_sub2_data, 0, NULL};
TableData TblHexSignificand_sub1_data[2] ={{DT_Subtable, &TblHexNumeral},{DT_Subtable, &TblHexSignificand_sub2}};
RuleTable TblHexSignificand_sub1 ={ET_Concatenate, RP_NA, 2, TblHexSignificand_sub1_data, 0, NULL};
TableData TblHexSignificand_sub4_data[1] ={{DT_Subtable, &TblHexDigits}};
RuleTable TblHexSignificand_sub4 ={ET_Zeroorone, RP_NA, 1, TblHexSignificand_sub4_data, 0, NULL};
TableData TblHexSignificand_sub3_data[4] ={{DT_String, {.mString="0x"}},{DT_Subtable, &TblHexSignificand_sub4},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblHexDigits}};
RuleTable TblHexSignificand_sub3 ={ET_Concatenate, RP_NA, 4, TblHexSignificand_sub3_data, 0, NULL};
TableData TblHexSignificand_sub6_data[1] ={{DT_Subtable, &TblHexDigits}};
RuleTable TblHexSignificand_sub6 ={ET_Zeroorone, RP_NA, 1, TblHexSignificand_sub6_data, 0, NULL};
TableData TblHexSignificand_sub5_data[4] ={{DT_String, {.mString="0X"}},{DT_Subtable, &TblHexSignificand_sub6},{DT_Token, {.mTokenId=43}},{DT_Subtable, &TblHexDigits}};
RuleTable TblHexSignificand_sub5 ={ET_Concatenate, RP_NA, 4, TblHexSignificand_sub5_data, 0, NULL};
TableData TblHexSignificand_data[3] ={{DT_Subtable, &TblHexSignificand_sub1},{DT_Subtable, &TblHexSignificand_sub3},{DT_Subtable, &TblHexSignificand_sub5}};
RuleTable TblHexSignificand ={ET_Oneof, RP_NA, 3, TblHexSignificand_data, 0, NULL};
TableData TblHexFPLiteral_sub1_data[1] ={{DT_Subtable, &TblFloatTypeSuffix}};
RuleTable TblHexFPLiteral_sub1 ={ET_Zeroorone, RP_NA, 1, TblHexFPLiteral_sub1_data, 0, NULL};
TableData TblHexFPLiteral_data[3] ={{DT_Subtable, &TblHexSignificand},{DT_Subtable, &TblBinaryExponent},{DT_Subtable, &TblHexFPLiteral_sub1}};
RuleTable TblHexFPLiteral ={ET_Concatenate, RP_NA, 3, TblHexFPLiteral_data, 0, NULL};
TableData TblFPLiteral_data[2] ={{DT_Subtable, &TblDecFPLiteral},{DT_Subtable, &TblHexFPLiteral}};
RuleTable TblFPLiteral ={ET_Oneof, RP_NA, 2, TblFPLiteral_data, 0, NULL};
TableData TblBooleanLiteral_data[2] ={{DT_String, {.mString="true"}},{DT_String, {.mString="false"}}};
RuleTable TblBooleanLiteral ={ET_Oneof, RP_NA, 2, TblBooleanLiteral_data, 0, NULL};
TableData TblCharacterLiteral_data[3] ={{DT_Char, {.mChar='\''}},{DT_Subtable, &TblCHAR},{DT_Char, {.mChar='\''}}};
RuleTable TblCharacterLiteral ={ET_Concatenate, RP_NA, 3, TblCharacterLiteral_data, 0, NULL};
TableData TblStringChar_data[2] ={{DT_Subtable, &TblASCII},{DT_Subtable, &TblESCAPE}};
RuleTable TblStringChar ={ET_Oneof, RP_NA, 2, TblStringChar_data, 0, NULL};
TableData TblStringLiteral_sub1_data[1] ={{DT_Subtable, &TblStringChar}};
RuleTable TblStringLiteral_sub1 ={ET_Zeroormore, RP_NA, 1, TblStringLiteral_sub1_data, 0, NULL};
TableData TblStringLiteral_data[3] ={{DT_Char, {.mChar='"'}},{DT_Subtable, &TblStringLiteral_sub1},{DT_Char, {.mChar='"'}}};
RuleTable TblStringLiteral ={ET_Concatenate, RP_NA, 3, TblStringLiteral_data, 0, NULL};
TableData TblNullLiteral_data[1] ={{DT_String, {.mString="null"}}};
RuleTable TblNullLiteral ={ET_Data, RP_NA, 1, TblNullLiteral_data, 0, NULL};
TableData TblLiteral_data[6] ={{DT_Subtable, &TblIntegerLiteral},{DT_Subtable, &TblFPLiteral},{DT_Subtable, &TblBooleanLiteral},{DT_Subtable, &TblCharacterLiteral},{DT_Subtable, &TblStringLiteral},{DT_Subtable, &TblNullLiteral}};
RuleTable TblLiteral ={ET_Oneof, RP_NA, 6, TblLiteral_data, 0, NULL};
